import {useCallback,useEffect,useRef,useState} from 'react';
import {clampMeter,type GameStats} from '../game/gameState';
import './BoohooLagoonMinigame.css';

type Sadness={id:number;x:number;gap:number;label:string;symbol:string;passed:boolean};
const themes=[['THE UNANSWERED MESSAGE','✉'],['THE EMPTY CHAIR','♧'],['THE OLD GOODBYE','◒'],['WHAT IF?','?'],['NOT ENOUGH','↓'],['THE ANNIVERSARY','⌛'],['THE WORDS UNSAID','…']] as const;
const fieldHeight=380,birdX=145,obstacleWidth=86,gapSize=142;
const makeSadness=(id:number,x:number):Sadness=>{const theme=themes[id%themes.length];return{id,x,gap:92+Math.random()*196,label:theme[0],symbol:theme[1],passed:false}};

export default function BoohooLagoonMinigame({stats,onChange,onExit}:{stats:GameStats;onChange:(stats:GameStats)=>void;onExit:()=>void}){
 const [bird,setBird]=useState(185),[obstacles,setObstacles]=useState<Sadness[]>(()=>[makeSadness(0,560),makeSadness(1,850)]),[score,setScore]=useState(0),[distance,setDistance]=useState(0),[failed,setFailed]=useState(false),[bestSpeed,setBestSpeed]=useState(150);
 const velocity=useRef(0),birdRef=useRef(bird),obstaclesRef=useRef(obstacles),failedRef=useRef(false),startTime=useRef(performance.now()),nextId=useRef(2),frame=useRef(0),last=useRef(performance.now());
 const flap=useCallback(()=>{if(!failedRef.current)velocity.current=-255},[]);
 useEffect(()=>{birdRef.current=bird},[bird]);
 useEffect(()=>{obstaclesRef.current=obstacles},[obstacles]);
 useEffect(()=>{failedRef.current=failed},[failed]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.code==='Space'||event.key==='ArrowUp'){event.preventDefault();flap()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[flap]);
 useEffect(()=>{const tick=(now:number)=>{const dt=Math.min(.034,(now-last.current)/1000);last.current=now;if(!failedRef.current){const elapsed=(now-startTime.current)/1000,speed=Math.min(430,150+elapsed*8.5);setBestSpeed(speed);velocity.current+=690*dt;const nextY=birdRef.current+velocity.current*dt;let next=obstaclesRef.current.map(item=>({...item,x:item.x-speed*dt}));const tail=next[next.length-1];if(tail&&tail.x<540)next.push(makeSadness(nextId.current++,tail.x+285));next=next.filter(item=>item.x>-obstacleWidth-20);let nextScore=score;next=next.map(item=>{if(!item.passed&&item.x+obstacleWidth<birdX){nextScore+=1;return{...item,passed:true}}return item});if(nextScore!==score)setScore(nextScore);const hit=nextY<15||nextY>fieldHeight-22||next.some(item=>item.x<birdX+27&&item.x+obstacleWidth>birdX-22&&(nextY-18<item.gap-gapSize/2||nextY+18>item.gap+gapSize/2));birdRef.current=Math.max(0,Math.min(fieldHeight,nextY));obstaclesRef.current=next;setBird(birdRef.current);setObstacles(next);setDistance(elapsed);if(hit){failedRef.current=true;setFailed(true)}}frame.current=requestAnimationFrame(tick)};frame.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame.current)},[score]);
 const retry=()=>{const fresh=[makeSadness(0,560),makeSadness(1,850)];velocity.current=0;birdRef.current=185;obstaclesRef.current=fresh;failedRef.current=false;startTime.current=performance.now();last.current=performance.now();nextId.current=2;setBird(185);setObstacles(fresh);setScore(0);setDistance(0);setBestSpeed(150);setFailed(false)};
 const finish=()=>{const clarity=Math.min(18,2+score*2),concentrationCost=Math.min(16,4+Math.floor(distance/7));onChange({...stats,clarity:clampMeter((stats.clarity??0)+clarity),confusion:clampMeter((stats.confusion??0)-Math.min(12,score)),concentration:clampMeter((stats.concentration??0)-concentrationCost)});onExit()};
 const rank=score>=12?'THE FAR SHORE GLIMMERS':score>=6?'YOU FLEW WITH THE WEATHER':score>=2?'DAMP, BUT AIRBORNE':'THE LAGOON HAS AN UNDERTOW';
 return <section className="boohoo-minigame"><header><small>BOOHOO LAGOON</small><h1>FLY BETWEEN THE SADNESSES</h1><p>Sadness may fill the sky without becoming the whole sky. Tap, click, or press SPACE to rise.</p></header><div className={`boohoo-flight ${failed?'failed':''}`} onPointerDown={event=>{event.preventDefault();flap()}}><div className="lagoon-moon"/><div className="distant-shore"/>{obstacles.map(item=><div className="sadness-obstacle" key={item.id} style={{left:`${item.x}px`}}><div className="sadness upper" style={{height:`${item.gap-gapSize/2}px`}}><i>{item.symbol}</i><b>{item.label}</b></div><div className="sadness lower" style={{top:`${item.gap+gapSize/2}px`}}><i>{item.symbol}</i><b>{item.label}</b></div></div>)}<div className="lagoon-familiar" style={{transform:`translate(${birdX}px,${bird}px) rotate(${Math.max(-24,Math.min(70,velocity.current/8))}deg)`}}><span>◆</span><i/><b/></div><div className="waterline"/><div className="flight-readout"><span>SADNESSES PASSED {score}</span><span>PACE ×{(bestSpeed/150).toFixed(1)}</span></div>{!failed&&<div className="flight-whisper">THE LAGOON QUICKENS…</div>}</div>{failed?<div className="lagoon-result"><small>THE WINGS TOUCH DARK WATER</small><h2>{rank}</h2><p>You passed <b>{score}</b> sadness{score===1?'':'es'}. The obstacle was real; the story that it filled the entire world was not.</p><div><button onClick={retry}>TRY THE SKY AGAIN</button><button onClick={finish}>CARRY THE CLARITY HOME</button></div></div>:<button className="lagoon-flap" onClick={flap}>FLAP THROUGH THE FEELING</button>}<button className="leave-lagoon" onClick={onExit}>RETREAT TO THE SHORE</button></section>;
}
