import {useCallback,useEffect,useRef,useState} from 'react';
import type {InteriorFloor,InteriorMap,InteriorZone} from '../data/interiorMaps';
import {movePlayer,type Player} from '../engine/movement';
import {drawPlayer} from '../rendering/drawPlayer';
import {drawVignette} from '../rendering/drawUI';
import './InteriorMode.css';

const palette={tower:['#171b2d','#28324a','#596279','#d5bd78'],fireworks:['#1b1020','#4a1830','#963b39','#ffb23e'],magick:['#16162d','#292957','#574f89','#c487d8'],jhana:['#10232a','#1f4650','#528071','#d0c77e'],divine:['#26324b','#5d5683','#a982a5','#f4d992'],formless:['#050711','#10142a','#24254d','#7881ba']} as const;
const zoneContains=(zone:InteriorZone,x:number,y:number)=>zone.shape==='circle'?Math.hypot((x-zone.x)/(zone.w/2),(y-zone.y)/(zone.h/2))<=1:Math.abs(x-zone.x)<=zone.w/2&&Math.abs(y-zone.y)<=zone.h/2;

function drawFloor(ctx:CanvasRenderingContext2D,map:InteriorMap,floor:InteriorFloor,art:HTMLImageElement|null,time:number){
 const p=palette[map.theme];ctx.fillStyle=p[0];ctx.fillRect(0,0,floor.width,floor.height);
 for(let y=0;y<floor.height;y+=48)for(let x=0;x<floor.width;x+=48){const n=Math.abs(Math.sin(x*12.989+y*78.233));ctx.fillStyle=n>.6?p[1]:p[0];ctx.fillRect(x+4,y+4,40,40);ctx.fillStyle=`${p[2]}33`;ctx.fillRect(x+10+(n*12|0),y+12,5,5)}
 ctx.save();ctx.strokeStyle=p[2];ctx.lineWidth=28;ctx.lineCap='round';ctx.globalAlpha=.45;ctx.beginPath();floor.zones.forEach((z,i)=>{if(!i)ctx.moveTo(floor.spawn[0],floor.spawn[1]);else ctx.moveTo(floor.zones[i-1].x,floor.zones[i-1].y);ctx.lineTo(z.x,z.y)});ctx.stroke();ctx.restore();
 floor.zones.forEach((z,i)=>{ctx.save();ctx.translate(z.x,z.y);ctx.fillStyle=`${p[1]}ee`;ctx.strokeStyle=p[3];ctx.lineWidth=5;if(z.shape==='circle'){ctx.beginPath();ctx.ellipse(0,0,z.w/2,z.h/2,0,0,Math.PI*2);ctx.fill();ctx.stroke()}else{ctx.fillRect(-z.w/2,-z.h/2,z.w,z.h);ctx.strokeRect(-z.w/2,-z.h/2,z.w,z.h)}ctx.restore();if(art){const cw=art.naturalWidth/5,ch=art.naturalHeight/4,size=Math.min(z.w,z.h)*.62;ctx.drawImage(art,z.art[0]*cw,z.art[1]*ch,cw,ch,z.x-size/2,z.y-size/2-8,size,size)}ctx.fillStyle='#15131ddd';const labelWidth=Math.min(z.w-12,ctx.measureText(z.name).width+18);ctx.fillRect(z.x-labelWidth/2,z.y+z.h/2-28,labelWidth,22);ctx.fillStyle='#fff0bd';ctx.font='bold 13px monospace';ctx.textAlign='center';ctx.fillText(z.name,z.x,z.y+z.h/2-12);ctx.fillStyle=p[3];ctx.fillRect(z.x-5,z.y-5+Math.sin(time/250+i)*3,10,10)});
 floor.obstacles.forEach((o,i)=>{ctx.fillStyle=p[1];ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle=p[3];ctx.lineWidth=4;ctx.strokeRect(o.x,o.y,o.w,o.h);for(let y=o.y+12;y<o.y+o.h-8;y+=22){ctx.fillStyle=i%2?p[2]:p[3];ctx.fillRect(o.x+12+(y%3)*6,y,o.w-30,7)}});
 const exitX=floor.spawn[0];ctx.fillStyle='#18151d';ctx.fillRect(exitX-70,floor.height-52,140,52);ctx.strokeStyle=p[3];ctx.lineWidth=5;ctx.strokeRect(exitX-70,floor.height-52,140,52);ctx.fillStyle='#fff0bd';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText('EXIT',exitX,floor.height-22);
 if(floor!==map.floors[map.floors.length-1])drawStairs(ctx,floor.width-100,100,'UP',p[3]);if(floor!==map.floors[0])drawStairs(ctx,100,100,'DOWN',p[3]);
}
function drawStairs(ctx:CanvasRenderingContext2D,x:number,y:number,label:string,color:string){ctx.fillStyle='#17141d';ctx.fillRect(x-45,y-45,90,90);ctx.strokeStyle=color;ctx.lineWidth=4;ctx.strokeRect(x-45,y-45,90,90);for(let i=0;i<5;i++){ctx.fillStyle=i%2?color:'#665b62';ctx.fillRect(x-32+i*6,y-28+i*10,64-i*12,7)}ctx.fillStyle='#fff0bd';ctx.font='bold 11px monospace';ctx.textAlign='center';ctx.fillText(label,x,y+37)}

export default function InteriorMode({map,onExit}:{map:InteriorMap;onExit:()=>void}){
 const canvasRef=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),player=useRef<Player>({x:map.floors[0].spawn[0],y:map.floors[0].spawn[1],direction:'up',moving:false,step:0}),activeZone=useRef<string|null>(null),transitionLock=useRef(0);
 const [floorIndex,setFloorIndex]=useState(0),[dialogue,setDialogue]=useState<InteriorZone|null>(null),[art,setArt]=useState<HTMLImageElement|null>(null);const floor=map.floors[floorIndex];
 const resize=useCallback(()=>{const c=canvasRef.current;if(!c)return;const d=devicePixelRatio||1,b=c.getBoundingClientRect();c.width=Math.round(b.width*d);c.height=Math.round(b.height*d)},[]);
 useEffect(()=>{const image=new Image();image.onload=()=>setArt(image);image.src=`${import.meta.env.BASE_URL}assets/interior-landmarks-v2.png`},[]);
 useEffect(()=>{resize();addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[resize]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k)){e.preventDefault();keys.current.add(k.startsWith('arrow')?e.key:k)}if(e.key==='Escape'){if(dialogue)setDialogue(null);else onExit()}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase().startsWith('arrow')?e.key:e.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[dialogue,onExit]);
 useEffect(()=>{player.current={x:floor.spawn[0],y:floor.spawn[1],direction:'up',moving:false,step:0};activeZone.current=null;transitionLock.current=performance.now()+700},[floor]);
 useEffect(()=>{let frame=0,last=performance.now();const tick=(now:number)=>{const c=canvasRef.current;if(!c)return;const dt=Math.min((now-last)/1000,.04);last=now;if(!dialogue){const before=player.current,next=movePlayer(before,keys.current,dt,floor.width,floor.height),blocked=floor.obstacles.some(o=>next.x+14>o.x&&next.x-14<o.x+o.w&&next.y+14>o.y&&next.y-14<o.y+o.h);player.current=blocked?{...before,direction:next.direction,moving:false}:next}const p=player.current;const entered=floor.zones.find(z=>zoneContains(z,p.x,p.y))??null;if(entered?.id!==(activeZone.current??undefined)){activeZone.current=entered?.id??null;if(entered)setDialogue(entered)}if(now>transitionLock.current&&!dialogue){if(Math.hypot(p.x-(floor.width-100),p.y-100)<48&&floorIndex<map.floors.length-1)setFloorIndex(i=>i+1);else if(Math.hypot(p.x-100,p.y-100)<48&&floorIndex>0)setFloorIndex(i=>i-1);else if(p.y>floor.height-38&&Math.abs(p.x-floor.spawn[0])<70)onExit()}const d=devicePixelRatio||1,w=c.width/d,h=c.height/d,camX=Math.max(0,Math.min(floor.width-w,p.x-w/2)),camY=Math.max(0,Math.min(floor.height-h,p.y-h/2)),ctx=c.getContext('2d')!;ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-camX,-camY);drawFloor(ctx,map,floor,art,now);drawPlayer(ctx,p);ctx.restore();drawVignette(ctx,w,h);frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[art,dialogue,floor,floorIndex,map,onExit]);
 const virtualKey=(key:string,pressed:boolean)=>pressed?keys.current.add(key):keys.current.delete(key);
 return <section className={`interior-mode theme-${map.theme}`}><canvas ref={canvasRef} tabIndex={0}/><header><button onClick={onExit}>← OVERWORLD</button><div><small>{map.name}</small><b>{floor.name}</b><span>{floor.subtitle}</span></div><em>{floorIndex+1}/{map.floors.length}</em></header><div className="interior-dpad" aria-label="Touch movement controls">{(['up','left','down','right'] as const).map(direction=>{const key=direction==='up'?'w':direction==='left'?'a':direction==='down'?'s':'d';return <button key={direction} className={direction} aria-label={`Move ${direction}`} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);virtualKey(key,true)}} onPointerUp={()=>virtualKey(key,false)} onPointerCancel={()=>virtualKey(key,false)}>{direction==='up'?'▲':direction==='left'?'◀':direction==='down'?'▼':'▶'}</button>})}</div>{dialogue&&<aside className="interior-dialogue" role="dialog"><button onClick={()=>setDialogue(null)}>×</button><p>PLACE DISCOVERED</p><h2>{dialogue.name}</h2><div/><span>◆ {dialogue.copy}</span><small>Close to keep exploring.</small></aside>}</section>
}
