import {useCallback,useEffect,useRef,useState} from 'react';
import type {InteriorFloor,InteriorMap,InteriorZone} from '../data/interiorMaps';
import {movePlayer,type Player} from '../engine/movement';
import {drawPlayer} from '../rendering/drawPlayer';
import {drawVignette} from '../rendering/drawUI';
import './InteriorMode.css';
import './InteriorNotifications.css';
import './InteriorHeaderFix.css';
import {getAtlas} from '../rendering/pixelArtAssets';

const palette={tower:['#111827','#28364b','#63718a','#d7c281'],fireworks:['#170d18','#481724','#96352e','#ffae38'],magick:['#11142b','#282954','#665b91','#c990df'],jhana:['#102126','#24464a','#64826d','#d2c981'],divine:['#252d49','#655b85','#a783a7','#f3db9a'],formless:['#03050d','#0d1228','#282a54','#8189c8'],healing:['#183229','#315c43','#70a66b','#d7d68e'],recall:['#21182a','#4b3b56','#86738e','#e2c589']} as const;
const themeColumn={tower:0,fireworks:3,magick:2,jhana:4,divine:5,formless:5,healing:4,recall:0};
const zoneContains=(z:InteriorZone,x:number,y:number)=>z.shape==='circle'?Math.hypot((x-z.x)/(z.w*.625),(y-z.y)/(z.h*.625))<=1:Math.abs(x-z.x)<=z.w*.625&&Math.abs(y-z.y)<=z.h*.625;
const upPoint=(floor:InteriorFloor):[number,number]=>{const z=floor.zones[floor.zones.length-1];return[z.x,Math.max(85,z.y-145)]};
const downPoint=(floor:InteriorFloor):[number,number]=>{const z=floor.zones[0];return[z.x,Math.min(floor.height-90,z.y+145)]};
const floorEntry=(map:InteriorMap,floor:InteriorFloor):InteriorZone=>({...floor.zones[0],id:`entry-${floor.id}`,name:floor.name,copy:`You have entered ${map.name}. ${floor.subtitle}.`});
const atlasCell=(ctx:CanvasRenderingContext2D,image:HTMLImageElement,column:number,row:number,x:number,y:number,size:number,alpha=1)=>{const w=image.naturalWidth/6,h=image.naturalHeight/4;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(image,column*w,row*h,w,h,x-size/2,y-size/2,size,size);ctx.restore()};
const recallCell=(ctx:CanvasRenderingContext2D,image:HTMLImageElement,column:number,x:number,y:number,size:number,alpha=1)=>{const w=image.naturalWidth/4,h=image.naturalHeight;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(image,column*w,0,w,h,x-size/2,y-size/2,size,size);ctx.restore()};

export function drawIntegratedFloor(ctx:CanvasRenderingContext2D,map:InteriorMap,floor:InteriorFloor,landmarks:HTMLImageElement|null,tiles:HTMLImageElement|null,time:number,floorIndex:number,special:HTMLImageElement|null=null,legacy:HTMLImageElement|null=null,states:HTMLImageElement|null=getAtlas('states'),rupa:HTMLImageElement|null=getAtlas('rupa')){
 const colors=palette[map.theme],column=themeColumn[map.theme],recallTiles=map.theme==='recall'?getAtlas('recall'):null,up=upPoint(floor),down=downPoint(floor),pathStart=floorIndex?down:floor.spawn,path=[pathStart,...floor.zones.map(z=>[z.x,z.y] as [number,number])];if(floorIndex<map.floors.length-1)path.push(up);
 ctx.fillStyle=colors[0];ctx.fillRect(0,0,floor.width,floor.height);
 ctx.save();ctx.globalAlpha=.42;for(let y=40;y<floor.height;y+=96)for(let x=40;x<floor.width;x+=96){const wave=Math.abs(Math.sin(x*.017+y*.023)),jitter=(wave*17|0);ctx.fillStyle=colors[2];ctx.fillRect(x-18+jitter,y-14,5+wave*7,4+wave*5);ctx.fillRect(x+22-jitter/2,y+18,3,3);if(recallTiles)recallCell(ctx,recallTiles,0,x,y,108,.52);else if(tiles&&((x/96+y/96)%3<1))atlasCell(ctx,tiles,column,0,x,y,104,.24)}ctx.restore();
 ctx.strokeStyle=`${colors[0]}b8`;ctx.lineWidth=172;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();path.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();ctx.strokeStyle=colors[1];ctx.lineWidth=158;ctx.stroke();ctx.strokeStyle=`${colors[3]}66`;ctx.lineWidth=3;ctx.setLineDash([10,20]);ctx.stroke();ctx.setLineDash([]);
 if(tiles||recallTiles)for(let i=0;i<path.length-1;i++){const [ax,ay]=path[i],[bx,by]=path[i+1];for(let t=.2;t<1;t+=.28){const x=ax+(bx-ax)*t,y=ay+(by-ay)*t;if(recallTiles)recallCell(ctx,recallTiles,1,x,y,98,.48);else if(tiles)atlasCell(ctx,tiles,column,1,x,y,88,.3)}}
 floor.zones.forEach((z,i)=>{const glow=ctx.createRadialGradient(z.x,z.y,15,z.x,z.y,Math.max(z.w,z.h)*.65);glow.addColorStop(0,`${colors[3]}75`);glow.addColorStop(.55,`${colors[2]}44`);glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(z.x,z.y,Math.max(z.w,z.h)*.65,0,Math.PI*2);ctx.fill();ctx.strokeStyle=`${colors[3]}66`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(z.x,z.y,Math.min(z.w,z.h)*.43+Math.sin(time/350+i)*3,0,Math.PI*2);ctx.stroke();const image=z.artAtlas==='special'?special:z.artAtlas==='legacy'?legacy:z.artAtlas==='states'?states:z.artAtlas==='rupa'?rupa:z.artAtlas==='luminous'?getAtlas('luminous'):landmarks;if(image){const columns=z.artAtlas==='luminous'?3:z.artAtlas==='states'||z.artAtlas==='special'||z.artAtlas==='rupa'?4:5,rows=z.artAtlas==='luminous'||z.artAtlas==='special'?2:z.artAtlas==='states'?3:z.artAtlas==='rupa'?1:z.artAtlas==='legacy'?5:4,size=Math.min(z.w,z.h)*.78,cellW=image.naturalWidth/columns,cellH=image.naturalHeight/rows;ctx.drawImage(image,z.art[0]*cellW,z.art[1]*cellH,cellW,cellH,z.x-size/2,z.y-size/2-10,size,size)}ctx.font='bold 13px monospace';ctx.textAlign='center';const label=Math.min(220,ctx.measureText(z.name).width+18);ctx.fillStyle='#11111abb';ctx.fillRect(z.x-label/2,z.y+z.h*.42-12,label,24);ctx.fillStyle='#fff0bd';ctx.fillText(z.name,z.x,z.y+z.h*.42+5)});
 floor.obstacles.forEach(o=>{if(recallTiles)recallCell(ctx,recallTiles,2,o.x+o.w/2,o.y+o.h/2,Math.max(o.w,o.h)*1.35);else if(tiles)atlasCell(ctx,tiles,column,2,o.x+o.w/2,o.y+o.h/2,Math.max(o.w,o.h)*1.35);else{ctx.fillStyle=colors[2];ctx.fillRect(o.x,o.y,o.w,o.h)}});
 if(floorIndex===0){if(recallTiles)recallCell(ctx,recallTiles,3,floor.spawn[0],floor.height-70,145);drawExit(ctx,floor.spawn[0],floor.height-35,colors[3])}else drawStairs(ctx,tiles,down[0],down[1],false,colors[3],map.theme);if(floorIndex<map.floors.length-1)drawStairs(ctx,tiles,up[0],up[1],true,colors[3],map.theme);
 ctx.strokeStyle=`${colors[2]}88`;ctx.lineWidth=6;ctx.strokeRect(22,22,floor.width-44,floor.height-44);ctx.strokeStyle=`${colors[3]}66`;ctx.lineWidth=2;ctx.strokeRect(31,31,floor.width-62,floor.height-62);
}
function drawStairs(ctx:CanvasRenderingContext2D,tiles:HTMLImageElement|null,x:number,y:number,up:boolean,color:string,theme:InteriorMap['theme']){if(tiles){const column=theme==='divine'?4:theme==='formless'?5:up?0:1;atlasCell(ctx,tiles,column,3,x,y,126);return}ctx.fillStyle='#17141d';ctx.fillRect(x-48,y-48,96,96);for(let i=0;i<6;i++){ctx.fillStyle=i%2?color:'#625b62';ctx.fillRect(x-34+i*5,y-31+i*10,68-i*10,7)}}
function drawExit(ctx:CanvasRenderingContext2D,x:number,y:number,color:string){ctx.fillStyle='#121019';ctx.fillRect(x-74,y-36,148,72);ctx.strokeStyle=color;ctx.lineWidth=5;ctx.strokeRect(x-74,y-36,148,72);ctx.fillStyle='#fff0bd';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText('MAIN MAP',x,y+5)}

export default function InteriorMode({map,onExit}:{map:InteriorMap;onExit:()=>void}){
 const canvasRef=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),player=useRef<Player>({x:map.floors[0].spawn[0],y:map.floors[0].spawn[1],direction:'up',moving:false,step:0}),activeZone=useRef<string|null>(null),transitionLock=useRef(0);
 const [floorIndex,setFloorIndex]=useState(0),[dialogue,setDialogue]=useState<InteriorZone|null>(null),[notice,setNotice]=useState<InteriorZone|null>(()=>floorEntry(map,map.floors[0])),[lastDiscovery,setLastDiscovery]=useState<InteriorZone|null>(null),[landmarks,setLandmarks]=useState<HTMLImageElement|null>(null),[tiles,setTiles]=useState<HTMLImageElement|null>(null),[special,setSpecial]=useState<HTMLImageElement|null>(null),[legacy,setLegacy]=useState<HTMLImageElement|null>(null);const floor=map.floors[floorIndex];
 const resize=useCallback(()=>{const c=canvasRef.current;if(!c)return;const d=devicePixelRatio||1,b=c.getBoundingClientRect();c.width=Math.round(b.width*d);c.height=Math.round(b.height*d)},[]);
 useEffect(()=>{const load=(file:string,setter:(image:HTMLImageElement)=>void)=>{const image=new Image();image.onload=()=>setter(image);image.src=`${import.meta.env.BASE_URL}assets/${file}`};load('interior-landmarks-v2.png',setLandmarks);load('environment-tiles-v3.png',setTiles);load('healing-jhana-landmarks.png',setSpecial);load('submaps-atlas.png',setLegacy)},[]);
 useEffect(()=>{resize();addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[resize]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k)){e.preventDefault();keys.current.add(k.startsWith('arrow')?e.key:k)}if(e.key==='Escape'){if(dialogue)setDialogue(null);else onExit()}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase().startsWith('arrow')?e.key:e.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[dialogue,onExit]);
 useEffect(()=>{const start=floorIndex===0?floor.spawn:downPoint(floor),entry=floorEntry(map,floor);player.current={x:start[0],y:floorIndex===0?start[1]:Math.min(floor.height-20,start[1]+65),direction:'up',moving:false,step:0};activeZone.current=null;setNotice(entry);setLastDiscovery(entry);transitionLock.current=performance.now()+850},[floor,floorIndex,map]);
 useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(current=>current?.id===notice.id?null:current),6500);return()=>clearTimeout(timer)},[notice]);
 useEffect(()=>{let frame=0,last=performance.now();const tick=(now:number)=>{const c=canvasRef.current;if(!c)return;const dt=Math.min((now-last)/1000,.04);last=now;if(!dialogue){const before=player.current,next=movePlayer(before,keys.current,dt,floor.width,floor.height),blocked=floor.obstacles.some(o=>next.x+14>o.x&&next.x-14<o.x+o.w&&next.y+14>o.y&&next.y-14<o.y+o.h);player.current=blocked?{...before,direction:next.direction,moving:false}:next}const p=player.current,entered=floor.zones.find(z=>zoneContains(z,p.x,p.y))??null;if(entered?.id!==(activeZone.current??undefined)){activeZone.current=entered?.id??null;if(entered){setNotice(entered);setLastDiscovery(entered)}}if(now>transitionLock.current&&!dialogue){const up=upPoint(floor),down=downPoint(floor);if(Math.hypot(p.x-up[0],p.y-up[1])<48&&floorIndex<map.floors.length-1)setFloorIndex(i=>i+1);else if(Math.hypot(p.x-down[0],p.y-down[1])<48&&floorIndex>0)setFloorIndex(i=>i-1);else if(floorIndex===0&&p.y>floor.height-55&&Math.abs(p.x-floor.spawn[0])<78)onExit()}const d=devicePixelRatio||1,w=c.width/d,h=c.height/d,camX=Math.max(0,Math.min(floor.width-w,p.x-w/2)),camY=Math.max(0,Math.min(floor.height-h,p.y-h/2)),ctx=c.getContext('2d')!;ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-camX,-camY);drawIntegratedFloor(ctx,map,floor,landmarks,tiles,now,floorIndex,special,legacy);drawPlayer(ctx,p);ctx.restore();drawVignette(ctx,w,h);frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[dialogue,floor,floorIndex,landmarks,legacy,map,onExit,special,tiles]);
 const virtualKey=(key:string,pressed:boolean)=>pressed?keys.current.add(key):keys.current.delete(key);
 const openLore=(zone:InteriorZone)=>{setDialogue(zone);setNotice(null);keys.current.clear()};
 return <section className={`interior-mode theme-${map.theme}`}><canvas ref={canvasRef} tabIndex={0}/><header><button type="button" onClick={onExit}>← MAIN MAP</button><div><small>{map.name}</small><b>{floor.name}</b><span>{floor.subtitle}</span></div><em>{floorIndex+1}/{map.floors.length}</em></header><div className="interior-dpad" aria-label="Touch movement controls">{(['up','left','down','right'] as const).map(direction=>{const key=direction==='up'?'w':direction==='left'?'a':direction==='down'?'s':'d';return <button type="button" key={direction} className={direction} aria-label={`Move ${direction}`} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);virtualKey(key,true)}} onPointerUp={()=>virtualKey(key,false)} onPointerCancel={()=>virtualKey(key,false)}>{direction==='up'?'▲':direction==='left'?'◀':direction==='down'?'▼':'▶'}</button>})}</div>{lastDiscovery&&!notice&&!dialogue&&<button type="button" className="lore-journal" onClick={()=>openLore(lastDiscovery)}>◆ LORE</button>}{notice&&<button type="button" className="area-notice" aria-label={`Open lore for ${notice.name}`} onPointerUp={()=>openLore(notice)}><small>NEW AREA ENTERED</small><b>{notice.name}</b><span>TAP FOR LORE →</span></button>}{dialogue&&<aside className="interior-dialogue" role="dialog" aria-label={dialogue.name}><button type="button" aria-label="Close lore" onClick={()=>setDialogue(null)}>×</button><p>PLACE LORE</p><h2>{dialogue.name}</h2><div/><span>◆ {dialogue.copy}</span><small>Close to keep exploring.</small></aside>}</section>
}
