import {useCallback,useEffect,useRef,useState} from 'react';
import type {EncounterOutcome,MistEncounterId} from '../game/encounterOutcome';
import type {PracticeKey,PracticeState} from '../game/dynamicWorld';
import {innDebaters,type DialogueEffect,type DialogueNode} from '../data/quarrelsomeConversations';
import './MistEncounters.css';
import './QuarrelsomeDialogues.css';

const outcomes={
 boohoo:{success:{grade:'success',title:'THE KINDLY SHORE',copy:'You let sorrow be weather instead of a wall. The Lagoon loosens its hold.',reason:'A compassionate shore appears beside the dark water.',stats:{clarity:9,confusion:-14,concentration:-3},practice:{equanimity:9,embodiment:6,integration:5,craving:-5},resolved:'booboo'},partial:{grade:'partial',title:'DAMP, BUT AFLOAT',copy:'You struck a few sad branches, yet did not build a home beneath them.',reason:'The Lagoon remains, but a muddy footpath reaches the Mist.',stats:{clarity:4,confusion:-3,concentration:-6},practice:{equanimity:4,integration:2},unresolved:'booboo'},failure:{grade:'failure',title:'DOWN IN THE DARK WATER',copy:'The sad things became the whole sky. Rest; this is an undertow, not a verdict.',reason:'Boohoo Lagoon swells and nearby roads bend back toward it.',stats:{confusion:20,concentration:-10},practice:{stability:-10,craving:7,embodiment:-5},unresolved:'booboo'}},
 chasm:{success:{grade:'success',title:'THE FAR ANCHOR',copy:'You crossed without demanding that the bridge stop moving.',reason:'The far side of the Chasm now touches steadier country.',stats:{clarity:9,confusion:-8,concentration:-7},practice:{stability:10,equanimity:9,deconstructiveClarity:5,integration:4},resolved:'chasm'},partial:{grade:'partial',title:'KNEES ON THE PLANKS',copy:'You crossed mostly by crawling. Dignity is lighter luggage than survival.',reason:'The bridge remains narrow, but it no longer vanishes completely.',stats:{clarity:4,confusion:2,concentration:-9},practice:{stability:4,equanimity:3},unresolved:'chasm'},failure:{grade:'failure',title:'THE ROPE SLIPS',copy:'Meaning drops away and the Mist catches you below. The bridge remembers the fall.',reason:'The Chasm widens; unstable roads lean toward its edge.',stats:{confusion:22,concentration:-13},practice:{stability:-14,equanimity:-4,embodiment:-5},unresolved:'chasm'}},
 clarity:{success:{grade:'success',title:'DISCERNMENT HOLDS',copy:'You separated what appeared from the story told about it. Certainty loses its crown.',reason:'A doubtful footpath opens away from counterfeit clarity.',stats:{clarity:12,confusion:-12,concentration:-5},practice:{realityTesting:15,deconstructiveClarity:9,craving:-10,equanimity:5},resolved:'counterfeit-crags'},partial:{grade:'partial',title:'A USEFUL MAYBE',copy:'Some glitter still passes for proof, but uncertainty has entered the room.',reason:'The Circuit develops an imperfect side road.',stats:{clarity:5,confusion:2,concentration:-6},practice:{realityTesting:6,craving:-3,deconstructiveClarity:3},unresolved:'counterfeit-crags'},failure:{grade:'failure',title:'CERTAINTY WINS THE ROUND',copy:'Every symbol signs its own certificate of truth. The Circuit applauds and closes behind you.',reason:'The Crags and Credulous Circuit pull together into a persuasive loop.',stats:{confusion:17,concentration:-7},practice:{realityTesting:-14,craving:14,stability:-5},unresolved:'credulous-circuit'}},
 inn:{success:{grade:'success',title:'A GOOD ARGUMENT ENDS',copy:'You kept the useful question and left the need to win beside the empty mugs.',reason:'A conversational road connects the Inn to integration and reality-testing.',stats:{clarity:7,confusion:-7,concentration:-3},practice:{realityTesting:8,integration:7,equanimity:6,craving:-5},resolved:'inn'},partial:{grade:'partial',title:'A DRAW, WITH BISCUITS',copy:'Nobody changed kingdoms, but one map gained a pencilled question mark.',reason:'The Inn remains noisy, though one window now faces the Mist.',stats:{clarity:3,confusion:1,concentration:-4},practice:{realityTesting:3,integration:2},unresolved:'inn'},failure:{grade:'failure',title:'THE TABLE IS NOW A PODIUM',copy:'The landscape disappears beneath increasingly accurate descriptions of the landscape.',reason:'Argument thickens the Mist and roads circle back to the Inn.',stats:{confusion:12,concentration:-6},practice:{craving:8,equanimity:-6,realityTesting:-4},unresolved:'inn'}},
 mist:{success:{grade:'success',title:'THE MURK ORGANIZES ITSELF',copy:'You waited without forcing a picture. A quiet contour becomes a trustworthy path.',reason:'Patient observation lets deconstructive roads emerge from the Murk.',stats:{clarity:8,confusion:-10,concentration:-4},practice:{equanimity:10,stability:7,deconstructiveClarity:6,craving:-9},resolved:'mist'},partial:{grade:'partial',title:'A SHAPE, THEN WEATHER',copy:'You chased one form, released another, and learned at least which gesture clouds the glass.',reason:'The Murk offers an intermittent road.',stats:{clarity:4,confusion:-2,concentration:-5},practice:{equanimity:4,craving:-3},unresolved:'mist'},failure:{grade:'failure',title:'THE MURK IS MANHANDLED',copy:'Every almost-shape is pulled apart to check whether it has arrived yet.',reason:'Forced imagery makes the Mist noisy and unstable.',stats:{confusion:15,concentration:-7},practice:{craving:10,stability:-8,generativeControl:4},unresolved:'mist'}}
} as const;

function Result({outcome,onComplete}:{outcome:EncounterOutcome;onComplete:(outcome:EncounterOutcome)=>void}){return <div className={`encounter-result ${outcome.grade}`}><small>{outcome.grade.toUpperCase()}</small><h2>{outcome.title}</h2><p>{outcome.copy}</p><button onClick={()=>onComplete(outcome)}>RETURN TO THE MISTS</button></div>}
const shell=(title:string,subtitle:string,content:React.ReactNode)=><section className="mist-game"><header><small>MISTS OF PURIFICATION</small><h1>{title}</h1><p>{subtitle}</p></header>{content}</section>;

function BoohooFlight({onComplete}:{onComplete:(outcome:EncounterOutcome)=>void}){
 const [bird,setBird]=useState(150),[velocity,setVelocity]=useState(0),[obstacles,setObstacles]=useState(()=>[{x:520,gap:135,label:'THE OLD MESSAGE'},{x:810,gap:190,label:'THE EMPTY CHAIR'},{x:1100,gap:115,label:'WHAT IF'},{x:1390,gap:175,label:'THE GOODBYE'},{x:1680,gap:145,label:'NOT ENOUGH'}]),[hits,setHits]=useState(0),[passed,setPassed]=useState(0),[result,setResult]=useState<EncounterOutcome|null>(null),hitIds=useRef(new Set<number>());
 const flap=useCallback(()=>setVelocity(-6.4),[]);
 useEffect(()=>{if(result)return;const down=(event:KeyboardEvent)=>{if(event.code==='Space'||event.key==='ArrowUp'){event.preventDefault();flap()}};addEventListener('keydown',down);return()=>removeEventListener('keydown',down)},[flap,result]);
 useEffect(()=>{if(result)return;const timer=window.setInterval(()=>{setVelocity(v=>Math.min(7.5,v+.55));setBird(y=>Math.max(15,Math.min(285,y+velocity)));setObstacles(items=>items.map(item=>({...item,x:item.x-7})));},45);return()=>clearInterval(timer)},[result,velocity]);
 useEffect(()=>{if(result)return;obstacles.forEach((item,index)=>{if(item.x<125&&item.x>65&&!hitIds.current.has(index)&&Math.abs(bird-item.gap)>58){hitIds.current.add(index);setHits(value=>value+1)}if(item.x<45&&!hitIds.current.has(100+index)){hitIds.current.add(100+index);setPassed(value=>value+1)}});if(obstacles.every(item=>item.x<-80)){const grade=hits===0?'success':hits<=2?'partial':'failure';setResult(outcomes.boohoo[grade] as EncounterOutcome)}},[bird,hits,obstacles,result]);
 return shell('BOOHOO LAGOON','SPACE / TAP to stay aloft. Sadness may be touched; do not build a nest in it.',<>{result?<Result outcome={result} onComplete={onComplete}/>:<><div className="boohoo-field" onPointerDown={flap}><div className="boohoo-bird" style={{top:bird}}>◆</div>{obstacles.map((item,index)=><div className="sad-obstacle" key={index} style={{left:item.x}}><i style={{height:item.gap-66}}/><b>{item.label}</b><i style={{top:item.gap+66}}/></div>)}</div><div className="encounter-score">SHORES PASSED {passed}/5 · SAD COLLISIONS {hits}</div><button className="encounter-action" onClick={flap}>FLAP THROUGH THE FEELING</button></>}</>)}

function ChasmBalance({onComplete}:{onComplete:(outcome:EncounterOutcome)=>void}){
 const [lean,setLean]=useState(0),[time,setTime]=useState(0),[falls,setFalls]=useState(0),[result,setResult]=useState<EncounterOutcome|null>(null),input=useRef(0);
 useEffect(()=>{if(result)return;const down=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft'||e.key==='a')input.current=-1;if(e.key==='ArrowRight'||e.key==='d')input.current=1},up=()=>input.current=0;addEventListener('keydown',down);addEventListener('keyup',up);const timer=window.setInterval(()=>{setTime(t=>t+1);setLean(value=>{const next=value+Math.sin(Date.now()/430)*.055+input.current*.09;if(Math.abs(next)>1){setFalls(f=>f+1);return 0}return next})},80);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up);clearInterval(timer)}},[result]);
 useEffect(()=>{if(time<250||result)return;const grade=falls===0?'success':falls<=2?'partial':'failure';setResult(outcomes.chasm[grade] as EncounterOutcome)},[falls,result,time]);
 const press=(direction:number)=>{input.current=direction};return shell('THE CHASM OF DESPAIR','Balance without insisting that the bridge become still.',result?<Result outcome={result} onComplete={onComplete}/>:<><div className="chasm-scene"><div className="chasm-depth"/><div className="rope-bridge" style={{transform:`rotate(${lean*13}deg)`}}><span style={{left:`${50+lean*34}%`}}>◆</span></div></div><div className="balance-meter"><i style={{left:`${50+lean*45}%`}}/></div><div className="encounter-score">CROSSING {Math.min(100,Math.round(time/2.5))}% · SLIPS {falls}</div><div className="encounter-buttons"><button onPointerDown={()=>press(-1)} onPointerUp={()=>press(0)}>◀ LEAN</button><button onPointerDown={()=>press(1)} onPointerUp={()=>press(0)}>LEAN ▶</button></div></>)}

const clarityCards=[['A face appears in the patterns.','EXPERIENCE'],['The face is an infallible external teacher.','INTERPRETATION'],['The colours pulse when attention changes.','EXPERIENCE'],['This proves the universe selected me personally.','INTERPRETATION'],['The scene feels astonishingly certain.','EXPERIENCE'],['Feeling certain guarantees the explanation is true.','INTERPRETATION'],['A symbol reminds me of an old fear.','EXPERIENCE'],['The symbol predicts exactly what everyone else must do.','INTERPRETATION']] as const;
function ClarityTrial({variant,onComplete}:{variant:'counterfeit-crags'|'credulous-circuit';onComplete:(outcome:EncounterOutcome)=>void}){const [index,setIndex]=useState(0),[score,setScore]=useState(0),[result,setResult]=useState<EncounterOutcome|null>(null);const answer=(choice:string)=>{const next=score+(choice===clarityCards[index][1]?1:0);if(index===clarityCards.length-1){const grade=next>=7?'success':next>=4?'partial':'failure',base=outcomes.clarity[grade] as EncounterOutcome;setResult({...base,resolved:grade==='success'?variant:undefined,unresolved:grade==='success'?undefined:variant})}else{setScore(next);setIndex(i=>i+1)}};return shell(variant==='counterfeit-crags'?'CRAGS OF COUNTERFEIT CLARITY':'CREDULOUS CLARITY CIRCUIT','Separate what appeared from what the mind concludes.',result?<Result outcome={result} onComplete={onComplete}/>:<div className="clarity-card"><small>DISCERNMENT {index+1}/{clarityCards.length}</small><p>{clarityCards[index][0]}</p><button onClick={()=>answer('EXPERIENCE')}>THIS IS AN EXPERIENCE</button><button onClick={()=>answer('INTERPRETATION')}>THIS IS AN INTERPRETATION</button><b>{score} distinctions held</b></div>)}

function QuarrelsomeArgument({practice,onComplete}:{practice:PracticeState;onComplete:(outcome:EncounterOutcome)=>void}){const [{debater,scenario}]=useState(()=>{const debater=innDebaters[Math.floor(Math.random()*innDebaters.length)];return{debater,scenario:debater.scenarios[Math.floor(Math.random()*debater.scenarios.length)]}}),[nodeId,setNodeId]=useState('start'),[totals,setTotals]=useState<{clarity:number;confusion:number;metta:number;practice:Partial<Record<PracticeKey,number>>}>({clarity:0,confusion:0,metta:0,practice:{}}),[result,setResult]=useState<EncounterOutcome|null>(null),node:DialogueNode=nodeId==='start'?{line:scenario.opening,replies:scenario.replies}:scenario.nodes[nodeId];const combine=(effect:DialogueEffect={})=>{const merged={...totals.practice};for(const [key,value] of Object.entries(effect.practice??{}) as [PracticeKey,number][])merged[key]=(merged[key]??0)+value;return{clarity:totals.clarity+(effect.clarity??0),confusion:totals.confusion+(effect.confusion??0),metta:totals.metta+(effect.metta??0),practice:merged}};const choose=(reply:typeof node.replies[number])=>{const nextTotals=combine(reply.effect);setTotals(nextTotals);if(reply.next){setNodeId(reply.next);return}if(!reply.ending)return;const ending=scenario.endings[reply.ending],finalTotals={...nextTotals,clarity:nextTotals.clarity+(ending.effect.clarity??0),confusion:nextTotals.confusion+(ending.effect.confusion??0),metta:nextTotals.metta+(ending.effect.metta??0),practice:{...nextTotals.practice}};for(const [key,value] of Object.entries(ending.effect.practice??{}) as [PracticeKey,number][])finalTotals.practice[key]=(finalTotals.practice[key]??0)+value;const base=outcomes.inn[ending.grade] as EncounterOutcome;setResult({...base,title:ending.title,copy:ending.copy,stats:{...base.stats,clarity:finalTotals.clarity,confusion:finalTotals.confusion,metta:finalTotals.metta},practice:{...base.practice,...finalTotals.practice}})};const replies=node.replies.filter(reply=>!reply.requires||practice[reply.requires.key]>=reply.requires.min);return shell('THE QUARRELSOME INN','Correct what matters, release what does not, and try not to become the furniture.',result?<Result outcome={result} onComplete={onComplete}/>:<div className="argument-stage"><div className="debater-portrait" style={{backgroundPosition:`${debater.sprite*25}% 50%`}}/><div className="argument-box"><small>{debater.name.toUpperCase()} · {debater.epithet}</small><p>“{node.line}”</p>{replies.map(reply=><button key={reply.text} onClick={()=>choose(reply)}>{reply.text}</button>)}</div></div>)}

function MurkObservation({onComplete}:{onComplete:(outcome:EncounterOutcome)=>void}){const [phase,setPhase]=useState(0),[score,setScore]=useState(0),[result,setResult]=useState<EncounterOutcome|null>(null);useEffect(()=>{if(result)return;const timer=window.setInterval(()=>setPhase(value=>(value+1)%3),1150);return()=>clearInterval(timer)},[result]);const observe=()=>{const next=score+(phase===2?2:phase===1?1:-1);if(Math.abs(next)>=6){const grade=next>=6?'success':next>=2?'partial':'failure';setResult(outcomes.mist[grade] as EncounterOutcome)}else setScore(next)};return shell('THE MURK','Wait for a form to dissolve before claiming to understand it.',result?<Result outcome={result} onComplete={onComplete}/>:<><div className={`murk-shape phase-${phase}`}><i/><b>{['EMERGING','SEEMING SOLID','DISSOLVING'][phase]}</b></div><button className="encounter-action" onClick={observe}>OBSERVE WITHOUT CORRECTING</button><div className="encounter-score">PATIENCE {score}</div></>)}

export default function MistEncounter({id,practice,onComplete,onExit}:{id:Exclude<MistEncounterId,'trauma'>;practice:PracticeState;onComplete:(outcome:EncounterOutcome)=>void;onExit:()=>void}){return <div className="mist-encounter-wrap">{id==='booboo'?<BoohooFlight onComplete={onComplete}/>:id==='chasm'?<ChasmBalance onComplete={onComplete}/>:id==='counterfeit-crags'||id==='credulous-circuit'?<ClarityTrial variant={id} onComplete={onComplete}/>:id==='inn'?<QuarrelsomeArgument practice={practice} onComplete={onComplete}/>:<MurkObservation onComplete={onComplete}/>}<button className="encounter-retreat" onClick={onExit}>RETREAT WITHOUT RESOLVING</button></div>}
