import {useState} from 'react';
import {clampMeter,type GameStats} from '../game/gameState';
import {innDebaters,validateInnDialogues,type DialogueEffect,type DialogueNode,type PracticeKey} from '../data/quarrelsomeConversations';
import './QuarrelsomeDialogues.css';
import './QuarrelsomeInnMinigame.css';

type Totals={clarity:number;confusion:number;metta:number;practice:Partial<Record<PracticeKey,number>>};
type ThreadTone='clear'|'warm'|'tangled';
const emptyTotals:Totals={clarity:0,confusion:0,metta:0,practice:{}};
const integrityIssues=validateInnDialogues();

export default function QuarrelsomeInnMinigame({stats,onChange,onExit}:{stats:GameStats;onChange:(stats:GameStats)=>void;onExit:()=>void}){
 const [{debater,scenario}]=useState(()=>{const debater=innDebaters[Math.floor(Math.random()*innDebaters.length)];return{debater,scenario:debater.scenarios[Math.floor(Math.random()*debater.scenarios.length)]}}),[nodeId,setNodeId]=useState('start'),[totals,setTotals]=useState<Totals>(emptyTotals),[result,setResult]=useState<{title:string;copy:string;grade:string;changes:Totals}|null>(null),[thread,setThread]=useState<ThreadTone[]>([]),[mood,setMood]=useState<'listening'|ThreadTone>('listening');
 const node:DialogueNode|undefined=nodeId==='start'?{line:scenario.opening,replies:scenario.replies}:scenario.nodes[nodeId];
 const combine=(effect:DialogueEffect={})=>{const practice={...totals.practice};for(const [key,value] of Object.entries(effect.practice??{}) as [PracticeKey,number][])practice[key]=(practice[key]??0)+value;return{clarity:totals.clarity+(effect.clarity??0),confusion:totals.confusion+(effect.confusion??0),metta:totals.metta+(effect.metta??0),practice}};
 const choose=(reply:NonNullable<typeof node>['replies'][number])=>{const effect=reply.effect??{},tone:ThreadTone=(effect.confusion??0)>Math.max(effect.clarity??0,effect.metta??0)?'tangled':(effect.metta??0)>(effect.clarity??0)?'warm':'clear';setMood(tone);setThread(value=>[...value,tone]);const next=combine(effect);setTotals(next);if(reply.next){if(scenario.nodes[reply.next])setNodeId(reply.next);else setResult({title:'A THREAD COMES LOOSE',copy:'The argument loses its place. You return to the Inn with the useful lesson that even conversational maps need checking.',grade:'partial',changes:next});return}if(!reply.ending)return;const ending=scenario.endings[reply.ending];if(!ending){setResult({title:'THE LAST WORD GOES MISSING',copy:'The conversation reaches an unmarked ending. Nothing is won, and the game remains standing.',grade:'partial',changes:next});return}const changes={...next,clarity:next.clarity+(ending.effect.clarity??0),confusion:next.confusion+(ending.effect.confusion??0),metta:next.metta+(ending.effect.metta??0),practice:{...next.practice}};for(const [key,value] of Object.entries(ending.effect.practice??{}) as [PracticeKey,number][])changes.practice[key]=(changes.practice[key]??0)+value;setResult({title:ending.title,copy:ending.copy,grade:ending.grade,changes})};
 const finish=()=>{if(!result)return;const p=result.changes.practice;onChange({...stats,clarity:clampMeter((stats.clarity??0)+result.changes.clarity),confusion:clampMeter((stats.confusion??0)+result.changes.confusion),concentration:clampMeter((stats.concentration??0)-(result.grade==='success'?3:result.grade==='partial'?4:6)),metta:clampMeter((stats.metta??0)+result.changes.metta+(p.metta??0)),equanimity:clampMeter((stats.equanimity??0)+(p.equanimity??0)),realityTesting:clampMeter((stats.realityTesting??0)+(p.realityTesting??0)),integration:clampMeter((stats.integration??0)+(p.integration??0)),craving:clampMeter((stats.craving??0)+(p.craving??0))});onExit()};
 const replies=node?.replies.filter(reply=>!reply.requires||(reply.requires.key==='metta'?(stats.metta??0):(stats.equanimity??0))>=reply.requires.min)??[];
 const unavailable=integrityIssues.length>0||!node;
 const room=<div className="inn-room" aria-hidden="true"><div className="inn-hearth"/><div className="inn-back-bar"><i/><b/></div><div className="inn-small-patron one"/><div className="inn-small-patron two"/><div className="argument-table"><i/><i/></div><div className="debater-portrait" style={{backgroundPosition:`${debater.sprite*25}% 50%`}}/><div className="inn-player-sprite"><i/><b/></div><div className="speech-runes">{thread.slice(-7).map((tone,index)=><i key={index} className={tone}/>)}</div></div>;
 return <section className={`inn-minigame inn-mood-${mood}`}><header><small>MISTS OF PURIFICATION · TABLE {debater.sprite+1}</small><h1>THE QUARRELSOME INN</h1><p>Correct what matters, release what does not, and try not to become the furniture.</p></header>{unavailable?<div className="inn-result partial"><small>THE INNKEEPER INTERVENES</small><h2>THE ARGUMENT NEEDS REPAIR</h2><p>A loose conversational thread was caught before it could tangle the whole game. Please try another table.</p><button onClick={onExit}>RETURN TO THE MISTS</button></div>:result?<><div className="result-room">{room}</div><div className={`inn-result ${result.grade}`}><small>{result.grade.toUpperCase()} · {thread.length} EXCHANGES</small><h2>{result.title}</h2><p>{result.copy}</p><button onClick={finish}>RETURN TO THE MISTS</button></div></>:<div className="argument-stage">{room}<div className="argument-box"><small>{debater.name.toUpperCase()} · {debater.epithet}</small><p>“{node.line}”</p><div className="conversation-thread"><span>CONVERSATION THREAD</span>{thread.length?<b>{thread.map((tone,index)=><i key={index} className={tone}/>)}</b>:<em>LISTENING…</em>}</div>{replies.map((reply,index)=><button key={reply.text} onClick={()=>choose(reply)}><span>{index+1}</span>{reply.text}</button>)}</div></div>}<button className="leave-inn" onClick={onExit}>LEAVE THE ARGUMENT</button></section>;
}
