import {useCallback,useEffect,useRef,useState} from 'react';
import {clampMeter,type GameStats} from '../game/gameState';
import './GameMode.css';

type Phase='candle'|'afterimage'|'dot'|'void';
const phaseCopy:Record<Phase,{title:string;instruction:string}>={candle:{title:'OPEN EYES · THE CANDLE',instruction:'Move the ring of attention around the flame. Hold it gently; do not squeeze.'},afterimage:{title:'CLOSED EYES · THE AFTERIMAGE',instruction:'The candle remains, colours reversed. Guide its wandering echo into the centre.'},dot:{title:'THE RED SIGN',instruction:'The candle simplifies into a red dot. Attend as colour shrinks and absence appears beneath it.'},void:{title:'THE CLOSING DARK',instruction:'The red has gone. Hold the dark absence at the centre as it closes.'}};
const lifeThoughts=['The garden still needs tending…','Why was everyone behaving so strangely earlier?','Did I remember to put that important thing somewhere safe?','Perhaps one quick snack would improve meditation.','What exactly did that person mean yesterday?','The candle will still be here after checking just one thing…'];
const distractions=[[0,0],[-122,-62],[126,-58],[-128,62],[118,68],[0,92]] as const;
const concentrationRate=(stats:GameStats,quality:number)=>{const diminishing=Math.pow(Math.max(.02,1-stats.concentration/100),1.45),clarityBoost=1+stats.clarity/45,barrierProgress=Math.max(0,Math.min(1,(stats.concentration-60)/10)),highBarrier=1-barrierProgress*(.92-stats.clarity/100);return quality*.65*diminishing*clarityBoost*highBarrier};

export default function RedDotMinigame({stats,onChange,onExit}:{stats:GameStats;onChange:(stats:GameStats)=>void;onExit:()=>void}){
 const keys=useRef(new Set<string>()),attention=useRef({x:70,y:-45,vx:0,vy:0}),target=useRef({x:0,y:0,vx:42,vy:-34}),distraction=useRef({x:-122,y:-62,next:0}),latest=useRef(stats),activation=useRef(0),stability=useRef(0),phaseRef=useRef<Phase>('candle'),readyRef=useRef(false),fadeUntil=useRef(0),lastPublish=useRef(0);
 const [phase,setPhase]=useState<Phase>('candle'),[thought,setThought]=useState(''),[display,setDisplay]=useState({activation:0,stability:0,ready:false,x:0,y:0,attentionX:70,attentionY:-45,attentionOpacity:1,concentration:stats.concentration});
 useEffect(()=>{latest.current={...stats}},[stats]);
 const publish=useCallback((now:number,force=false)=>{if(force||now-lastPublish.current>240){lastPublish.current=now;onChange({...latest.current})}},[onChange]);
 const enterPhase=useCallback((next:Phase)=>{phaseRef.current=next;setPhase(next);stability.current=0;readyRef.current=false;target.current={x:next==='afterimage'?18:0,y:next==='afterimage'?-12:0,vx:38+Math.random()*20,vy:-32-Math.random()*18};setThought('')},[]);
 const eyesAction=useCallback(()=>{if(phaseRef.current==='candle'){if(activation.current>=100)enterPhase('afterimage');return}activation.current=0;attention.current={x:65,y:-40,vx:0,vy:0};enterPhase('candle')},[enterPhase]);
 useEffect(()=>{const down=(event:KeyboardEvent)=>{const key=event.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(key)){event.preventDefault();keys.current.add(key.startsWith('arrow')?event.key:key)}if(event.code==='Space'){event.preventDefault();eyesAction()}};const up=(event:KeyboardEvent)=>keys.current.delete(event.key.toLowerCase().startsWith('arrow')?event.key:event.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[eyesAction]);
 useEffect(()=>{let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(.04,(now-last)/1000);last=now;let dx=0,dy=0,quality=0;if(keys.current.has('ArrowLeft')||keys.current.has('a'))dx--;if(keys.current.has('ArrowRight')||keys.current.has('d'))dx++;if(keys.current.has('ArrowUp')||keys.current.has('w'))dy--;if(keys.current.has('ArrowDown')||keys.current.has('s'))dy++;const length=Math.hypot(dx,dy)||1;
  if(phaseRef.current==='candle'){const a=attention.current,c=latest.current.concentration;if(c>=10){setThought('');fadeUntil.current=0}if(now>distraction.current.next){const point=distractions[Math.floor(Math.random()*distractions.length)];distraction.current={x:point[0],y:point[1],next:now+1200+c*35+Math.random()*1600};if(c<10){setThought(lifeThoughts[Math.floor(Math.random()*lifeThoughts.length)]);if(Math.random()>(c/10)*.72){a.x=point[0]+(Math.random()-.5)*28;a.y=point[1]+(Math.random()-.5)*22;a.vx=0;a.vy=0}if(c<3&&Math.random()<.55)fadeUntil.current=now+650+Math.random()*900}else setThought('')}
   const wander=Math.max(.04,1-c/100),pull=c<10?34:15*wander;a.vx+=(distraction.current.x-a.x)*pull*.018*dt+(Math.random()-.5)*wander*22*dt;a.vy+=(distraction.current.y-a.y)*pull*.018*dt+(Math.random()-.5)*wander*22*dt;a.vx*=Math.pow(.15,dt);a.vy*=Math.pow(.15,dt);a.x+=a.vx*dt+dx/length*135*dt;a.y+=a.vy*dt+dy/length*135*dt;a.x=Math.max(-150,Math.min(150,a.x));a.y=Math.max(-105,Math.min(105,a.y));const distance=Math.hypot(a.x,a.y);quality=distance<32?1:distance<52?.42:0;activation.current=Math.max(0,Math.min(100,activation.current+(quality?24*quality:-5)*dt))}
  else if(!readyRef.current){const p=target.current,force=155;p.vx+=dx/length*force*dt;p.vy+=dy/length*force*dt;const escape=.65+Math.max(0,(35-latest.current.concentration)/70);p.vx+=Math.sign(p.x||1)*escape*dt*18+(Math.random()-.5)*24*dt;p.vy+=Math.sign(p.y||-1)*escape*dt*18+(Math.random()-.5)*24*dt;p.vx*=.996;p.vy*=.996;p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.abs(p.x)>145){p.x=Math.sign(p.x)*145;p.vx*=-.72}if(Math.abs(p.y)>105){p.y=Math.sign(p.y)*105;p.vy*=-.72}const distance=Math.hypot(p.x,p.y);quality=distance<34?1:distance<58?.28:0;if(phaseRef.current==='afterimage')stability.current=Math.max(0,Math.min(100,stability.current+(quality?100/3*quality:-18)*dt));else if(phaseRef.current==='dot')stability.current=Math.min(100,stability.current+5*dt);else stability.current=Math.min(100,stability.current+10*dt);if(stability.current>=100){if(phaseRef.current==='afterimage')enterPhase('dot');else if(phaseRef.current==='dot')enterPhase('void');else readyRef.current=true}}
  if(quality>0){latest.current.concentration=clampMeter(latest.current.concentration+concentrationRate(latest.current,quality)*dt);publish(now)}const p=target.current,a=attention.current;setDisplay({activation:activation.current,stability:stability.current,ready:readyRef.current,x:p.x,y:p.y,attentionX:a.x,attentionY:a.y,attentionOpacity:now<fadeUntil.current?.15:1,concentration:latest.current.concentration});frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);publish(performance.now(),true)}},[enterPhase,publish]);
 const virtual=(key:string,pressed:boolean)=>pressed?keys.current.add(key):keys.current.delete(key),dotRatio=1-display.stability/100;
 return <section className={`red-dot-game phase-${phase}`} role="dialog" aria-label="Red Dot Practice"><header><small>RED DOT RANGE</small><h2>{phaseCopy[phase].title}</h2><p className={thought?'mind-wandering':''}>{thought||phaseCopy[phase].instruction}</p></header><div className="focus-field candle-chamber"><div className="closed-eye-shade"/>{phase==='candle'&&<div className="attention-ring" style={{opacity:display.attentionOpacity,transform:`translate(calc(-50% + ${display.attentionX}px),calc(-50% + ${display.attentionY}px))`}}/>}{phase==='afterimage'&&<div className="afterimage-candle" style={{transform:`translate(calc(-50% + ${display.x}px),calc(-50% + ${display.y}px))`}}><i/><b/></div>}{phase==='dot'&&<><div className="focus-void emerging" style={{width:8+22*(1-dotRatio),height:8+22*(1-dotRatio),transform:`translate(calc(-50% + ${display.x}px),calc(-50% + ${display.y}px))`}}/><div className={`focus-dot ${display.stability>18?'settled':''}`} style={{opacity:dotRatio,transform:`translate(calc(-50% + ${display.x}px),calc(-50% + ${display.y}px)) scale(${dotRatio})`}}/></>}{phase==='void'&&<div className={`focus-void ${display.ready?'closed':''}`} style={{width:Math.max(3,30*dotRatio),height:Math.max(3,30*dotRatio),transform:`translate(calc(-50% + ${display.x}px),calc(-50% + ${display.y}px))`}}/>}{phase!=='candle'&&<div className="focus-center"/>}<div className="candle-flicker"/></div><div className="practice-meter"><span>CONCENTRATION</span><div><i style={{width:`${display.concentration}%`}}/></div><b>{Math.round(display.concentration)}</b></div><div className="practice-controls">{([['up','ArrowUp','▲'],['left','ArrowLeft','◀'],['down','ArrowDown','▼'],['right','ArrowRight','▶']] as const).map(([direction,key,glyph])=><button key={direction} className={direction} onPointerDown={event=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);virtual(key,true)}} onPointerUp={()=>virtual(key,false)} onPointerCancel={()=>virtual(key,false)}>{glyph}</button>)}</div>{phase==='candle'&&display.activation>=100&&<button className="eyes-action" onClick={eyesAction}>SPACE · CLOSE THE EYES</button>}{phase!=='candle'&&<button className="eyes-action" onClick={eyesAction}>SPACE · OPEN THE EYES</button>}<button className="leave-practice" onClick={onExit}>RETURN TO THE RANGE</button></section>
}
