import {useEffect,useRef,useState} from 'react';
import {clampMeter,type GameStats} from '../game/gameState';
import './GameMode.css';

export default function RedDotMinigame({stats,onChange,onExit}:{stats:GameStats;onChange:(stats:GameStats)=>void;onExit:()=>void}){
 const dot=useRef({x:0,y:0,vx:42,vy:-34}),keys=useRef(new Set<string>()),latest=useRef(stats),[display,setDisplay]=useState(stats.concentration);
 useEffect(()=>{latest.current=stats},[stats]);
 useEffect(()=>{const down=(event:KeyboardEvent)=>{const key=event.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(key)){event.preventDefault();keys.current.add(key.startsWith('arrow')?event.key:key)}};const up=(event:KeyboardEvent)=>keys.current.delete(event.key.toLowerCase().startsWith('arrow')?event.key:event.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[]);
 useEffect(()=>{let frame=0,last=performance.now(),publish=last;const tick=(now:number)=>{const dt=Math.min(.04,(now-last)/1000);last=now;const p=dot.current,force=150;if(keys.current.has('ArrowLeft')||keys.current.has('a'))p.vx-=force*dt;if(keys.current.has('ArrowRight')||keys.current.has('d'))p.vx+=force*dt;if(keys.current.has('ArrowUp')||keys.current.has('w'))p.vy-=force*dt;if(keys.current.has('ArrowDown')||keys.current.has('s'))p.vy+=force*dt;const escape=.55+Math.min(1.1,latest.current.concentration/90);p.vx+=Math.sign(p.x||1)*escape*dt*18+(Math.random()-.5)*22*dt;p.vy+=Math.sign(p.y||-1)*escape*dt*18+(Math.random()-.5)*22*dt;p.vx*=.996;p.vy*=.996;p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.abs(p.x)>145){p.x=Math.sign(p.x)*145;p.vx*=-.72}if(Math.abs(p.y)>115){p.y=Math.sign(p.y)*115;p.vy*=-.72}const distance=Math.hypot(p.x,p.y),gain=distance<24?8:distance<55?4:distance<90?1.25:0;latest.current={...latest.current,concentration:clampMeter(latest.current.concentration+gain*dt)};setDisplay(latest.current.concentration);if(now-publish>250){publish=now;onChange(latest.current)}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);onChange(latest.current)}},[onChange]);
 const virtual=(key:string,pressed:boolean)=>pressed?keys.current.add(key):keys.current.delete(key);
 return <section className="red-dot-game" role="dialog" aria-label="Red Dot Practice"><header><small>RED DOT RANGE</small><h2>STEADY THE WANDERING FIRE</h2><p>Use the arrows to keep the red dot inside the golden centre.</p></header><div className="focus-field"><div className="focus-rings"/><div className="focus-dot" style={{transform:`translate(calc(-50% + ${dot.current.x}px),calc(-50% + ${dot.current.y}px))`}}/><div className="focus-center"/></div><div className="practice-meter"><span>CONCENTRATION</span><div><i style={{width:`${display}%`}}/></div><b>{Math.round(display)}</b></div><div className="practice-controls">{([['up','ArrowUp','▲'],['left','ArrowLeft','◀'],['down','ArrowDown','▼'],['right','ArrowRight','▶']] as const).map(([direction,key,label])=><button key={direction} className={direction} onPointerDown={event=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);virtual(key,true)}} onPointerUp={()=>virtual(key,false)} onPointerCancel={()=>virtual(key,false)}>{label}</button>)}</div><button className="leave-practice" onClick={onExit}>RETURN TO THE RANGE</button></section>
}
