import {useCallback,useEffect,useRef,useState} from 'react';
import {clampMeter,type GameStats} from '../game/gameState';
import './GameMode.css';

type Phase='candle'|'afterimage'|'dot'|'void';
const phaseCopy:Record<Phase,{title:string;instruction:string}>={
 candle:{title:'OPEN EYES · THE CANDLE',instruction:'Move the ring of attention around the flame. Hold it gently; do not squeeze.'},
 afterimage:{title:'CLOSED EYES · THE AFTERIMAGE',instruction:'The candle remains, colours reversed. Guide its wandering echo into the centre.'},
 dot:{title:'THE RED SIGN',instruction:'The candle simplifies into a red dot. Keep the little fire from escaping.'},
 void:{title:'THE CLOSING DARK',instruction:'The dot contracts into a dark absence. Hold even this at the centre until it closes.'}
};

export default function RedDotMinigame({stats,onChange,onExit}:{stats:GameStats;onChange:(stats:GameStats)=>void;onExit:()=>void}){
 const keys=useRef(new Set<string>()),attention=useRef({x:70,y:-45}),target=useRef({x:0,y:0,vx:42,vy:-34}),latest=useRef(stats),activation=useRef(0),stability=useRef(0),phaseRef=useRef<Phase>('candle'),cyclesRef=useRef(0),readyRef=useRef(false);
 const [phase,setPhase]=useState<Phase>('candle'),[display,setDisplay]=useState({activation:0,stability:0,cycles:0,ready:false,x:0,y:0,attentionX:70,attentionY:-45});latest.current=stats;
 const enterPhase=useCallback((next:Phase)=>{phaseRef.current=next;setPhase(next);stability.current=0;readyRef.current=false;target.current={x:next==='afterimage'?18:0,y:next==='afterimage'?-12:0,vx:38+(Math.random()*20),vy:-32-(Math.random()*18)}},[]);
 const eyesAction=useCallback(()=>{if(phaseRef.current==='candle'&&activation.current>=100)enterPhase('afterimage');else if(phaseRef.current==='void'&&readyRef.current){cyclesRef.current++;const next={...latest.current,concentration:clampMeter(latest.current.concentration+20)};latest.current=next;onChange(next);activation.current=0;attention.current={x:65,y:-40};enterPhase('candle')}},[enterPhase,onChange]);
 useEffect(()=>{const down=(event:KeyboardEvent)=>{const key=event.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(key)){event.preventDefault();keys.current.add(key.startsWith('arrow')?event.key:key)}if(event.code==='Space'){event.preventDefault();eyesAction()}};const up=(event:KeyboardEvent)=>keys.current.delete(event.key.toLowerCase().startsWith('arrow')?event.key:event.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up)}},[eyesAction]);
 useEffect(()=>{let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(.04,(now-last)/1000);last=now;let dx=0,dy=0;if(keys.current.has('ArrowLeft')||keys.current.has('a'))dx--;if(keys.current.has('ArrowRight')||keys.current.has('d'))dx++;if(keys.current.has('ArrowUp')||keys.current.has('w'))dy--;if(keys.current.has('ArrowDown')||keys.current.has('s'))dy++;const length=Math.hypot(dx,dy)||1;
  if(phaseRef.current==='candle'){const a=attention.current;a.x=Math.max(-150,Math.min(150,a.x+dx/length*135*dt));a.y=Math.max(-105,Math.min(105,a.y+dy/length*135*dt));const distance=Math.hypot(a.x,a.y);activation.current=Math.max(0,Math.min(100,activation.current+(distance<32?24:distance<52?10:-5)*dt))}
  else if(!readyRef.current){const p=target.current,force=155;p.vx+=dx/length*force*dt;p.vy+=dy/length*force*dt;const escape=.65+cyclesRef.current*.12;p.vx+=Math.sign(p.x||1)*escape*dt*18+(Math.random()-.5)*24*dt;p.vy+=Math.sign(p.y||-1)*escape*dt*18+(Math.random()-.5)*24*dt;p.vx*=.996;p.vy*=.996;p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.abs(p.x)>145){p.x=Math.sign(p.x)*145;p.vx*=-.72}if(Math.abs(p.y)>105){p.y=Math.sign(p.y)*105;p.vy*=-.72}const distance=Math.hypot(p.x,p.y),needed=phaseRef.current==='afterimage'?3:phaseRef.current==='dot'?4:3.2;stability.current=Math.max(0,Math.min(100,stability.current+(distance<34?100/needed:-18)*dt));if(stability.current>=100){if(phaseRef.current==='afterimage')enterPhase('dot');else if(phaseRef.current==='dot')enterPhase('void');else readyRef.current=true}}
  const p=target.current,a=attention.current;setDisplay({activation:activation.current,stability:stability.current,cycles:cyclesRef.current,ready:readyRef.current,x:p.x,y:p.y,attentionX:a.x,attentionY:a.y});frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[enterPhase]);
 const virtual=(key:string,pressed:boolean)=>pressed?keys.current.add(key):keys.current.delete(key);
 const metric=phase==='candle'?display.activation:display.stability,label=phase==='candle'?'VISUAL FIELD ACTIVATION':'STEADINESS';
 return <section className={`red-dot-game phase-${phase}`} role="dialog" aria-label="Red Dot Practice"><header><small>RED DOT RANGE · CYCLE {display.cycles+1}</small><h2>{phaseCopy[phase].title}</h2><p>{phaseCopy[phase].instruction}</p></header><div className="focus-field candle-chamber"><div className="closed-eye-shade"/>{phase==='candle'&&<div className="attention-ring" style={{transform:`translate(calc(-50% + ${display.attentionX}px),calc(-50% + ${display.attentionY}px))`}}/>}{phase==='afterimage'&&<div className="afterimage-candle" style={{transform:`translate(calc(-50% + ${display.x}px),calc(-50% + ${display.y}px))`}}><i/><b/></div>}{phase==='dot'&&<div className="focus-dot" style={{transform:`translate(calc(-50% + ${display.x}px),calc(-50% + ${display.y}px))`}}/>}{phase==='void'&&<div className={`focus-void ${display.ready?'closed':''}`} style={{transform:`translate(calc(-50% + ${display.x}px),calc(-50% + ${display.y}px))`}}/>}{phase!=='candle'&&<div className="focus-center"/>}<div className="candle-flicker"/></div><div className="practice-meter"><span>{label}</span><div><i style={{width:`${metric}%`}}/></div><b>{Math.round(metric)}</b></div><div className="cycle-progress"><span className={display.cycles>=1?'complete':''}>CYCLE I</span><span className={display.cycles>=2?'complete':''}>CYCLE II</span><b>{display.cycles>=2?'MIST-READY':'TWO CYCLES OPEN THE WAY'}</b></div><div className="practice-controls">{([['up','ArrowUp','▲'],['left','ArrowLeft','◀'],['down','ArrowDown','▼'],['right','ArrowRight','▶']] as const).map(([direction,key,glyph])=><button key={direction} className={direction} onPointerDown={event=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);virtual(key,true)}} onPointerUp={()=>virtual(key,false)} onPointerCancel={()=>virtual(key,false)}>{glyph}</button>)}</div>{phase==='candle'&&display.activation>=100&&<button className="eyes-action" onClick={eyesAction}>SPACE · CLOSE THE EYES</button>}{phase==='void'&&display.ready&&<button className="eyes-action" onClick={eyesAction}>SPACE · OPEN THE EYES</button>}<button className="leave-practice" onClick={onExit}>RETURN TO THE RANGE</button></section>
}
