import {useCallback,useEffect,useRef,useState} from 'react';
import {clampMeter,type GameStats} from '../game/gameState';
import './GameMode.css';

const maze=['###############','#S#.....#.....#','#.#.###.#.###.#','#...#...#...#.#','###.#.#####.#.#','#...#.....#.#.#','#.#######.#.#.#','#.....#...#...#','#.###.#.#####.#','#...#........E#','###############'];
const symbols=new Map<string,string>([['3,1','♢'],['7,3','⚡'],['11,3','⌁'],['5,5','◐'],['9,5','☂'],['5,7','✧'],['11,7','◒'],['7,9','⛓']]);
const directions={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]} as const;
const opposite:Record<keyof typeof directions,keyof typeof directions>={ArrowUp:'ArrowDown',ArrowDown:'ArrowUp',ArrowLeft:'ArrowRight',ArrowRight:'ArrowLeft',w:'s',s:'w',a:'d',d:'a'};
const phaseOpen=[new Set(['4,1','8,5']),new Set(['6,7','12,5'])];

export default function TraumaLabyrinth({stats,onChange,onExit}:{stats:GameStats;onChange:(stats:GameStats)=>void;onExit:()=>void}){
 const latest=useRef(stats),checkpoint=useRef({x:1,y:1}),reverseMoves=useRef(0),[position,setPosition]=useState({x:1,y:1}),[complete,setComplete]=useState(false),[grounded,setGrounded]=useState(false),[shifted,setShifted]=useState(false),[message,setMessage]=useState('The walls remember. Their symbols are rules, not decorations.');latest.current=stats;
 useEffect(()=>{if(complete)return;const timer=window.setInterval(()=>{const next={...latest.current,concentration:clampMeter(latest.current.concentration-.45)};latest.current=next;onChange(next)},1000);return()=>clearInterval(timer)},[complete,onChange]);
 const move=useCallback((raw:keyof typeof directions)=>{if(complete)return;const key=reverseMoves.current>0?opposite[raw]:raw;if(reverseMoves.current>0)reverseMoves.current--;const [dx,dy]=directions[key],x=position.x+dx,y=position.y+dy,cellKey=`${x},${y}`,baseWall=maze[y]?.[x]==='#',opened=phaseOpen[shifted?1:0].has(cellKey);if(baseWall&&!opened){setMessage('Stone. The passage does not exist in this version of the tunnel.');return}if(cellKey==='5,5'){setMessage('The Half-Seen Face freezes the passage. Another route remains.');return}if(cellKey==='7,9'&&!grounded){setMessage('Old Bindings bar the final corridor. Find the Grounding Star first.');return}const nextStats={...latest.current,concentration:clampMeter(latest.current.concentration-.65)};latest.current=nextStats;onChange(nextStats);let destination={x,y};
  if(cellKey==='3,1'||cellKey==='7,3'){destination={x:1,y:1};checkpoint.current={x:1,y:1};setMessage(cellKey==='3,1'?'The False Door opens onto the beginning.':'A Flashback tears the route away. You awaken at the entrance.')}
  else if(cellKey==='11,3'){reverseMoves.current=8;setMessage('The Echo Knot reverses the next eight steps. Left remembers right; forward remembers back.')}
  else if(cellKey==='9,5'){const nextShift=!shifted;setShifted(nextShift);checkpoint.current={x,y};setMessage(`The Shelter Switch turns. Stone passages ${nextShift?'B':'A'} become real.`)}
  else if(cellKey==='5,7'&&!grounded){setGrounded(true);setMessage('Grounding Star found. Name the room, feel your feet: the Old Bindings can now open.')}
  else if(cellKey==='11,7'){destination=checkpoint.current;setMessage('The Repeating Scene returns you to the last shelter—but not all the way to the beginning.')}
  setPosition(destination);if(maze[y]?.[x]==='E'){const reward={...nextStats,clarity:clampMeter(nextStats.clarity+18)};latest.current=reward;onChange(reward);setComplete(true);setMessage('The Lantern-Door opens. The tunnel is remembered, but it is no longer the whole world.')}},[complete,grounded,onChange,position,shifted]);
 useEffect(()=>{const down=(event:KeyboardEvent)=>{const key=(event.key.length===1?event.key.toLowerCase():event.key) as keyof typeof directions;if(key in directions){event.preventDefault();move(key)}};addEventListener('keydown',down);return()=>removeEventListener('keydown',down)},[move]);
 const openCells=phaseOpen[shifted?1:0];
 return <section className="trauma-game" role="dialog" aria-label="Trauma Tunnels Labyrinth"><header><small>THE TRAUMA TUNNELS</small><h2>THE LABYRINTH OF ECHOES</h2><p>{message}</p></header><div className="trauma-layout"><div className="maze" style={{gridTemplateColumns:`repeat(${maze[0].length},1fr)`}}>{maze.flatMap((row,y)=>[...row].map((cell,x)=>{const key=`${x},${y}`,symbol=symbols.get(key),here=position.x===x&&position.y===y,isOpen=openCells.has(key),wall=cell==='#'&&!isOpen,locked=key==='7,9'&&!grounded;return <div key={key} className={`maze-cell ${wall?'wall':'floor'} ${isOpen?'shift-passage':''} ${cell==='E'?'exit':''} ${locked?'locked':''}`}>{symbol&&<span>{symbol}</span>}{cell==='E'&&<b>◇</b>}{here&&<i>◆</i>}</div>}))}</div><aside className="trauma-symbols"><b>THE SYMBOLS HAVE RULES</b><span>♢ False Door · beginning</span><span>⚡ Flashback · beginning</span><span>◐ Half-Seen Face · blocks</span><span>⌁ Echo Knot · reverses steps</span><span>☂ Shelter Switch · shifts walls</span><span>✧ Grounding Star · opens bindings</span><span>◒ Repeating Scene · checkpoint</span><span>⛓ Old Bindings · locked path</span></aside></div><div className="trauma-readout"><span>CONCENTRATION</span><div><i style={{width:`${latest.current.concentration}%`}}/></div><b>{Math.round(latest.current.concentration)}</b></div><div className="trauma-controls">{([['up','ArrowUp','▲'],['left','ArrowLeft','◀'],['down','ArrowDown','▼'],['right','ArrowRight','▶']] as const).map(([direction,key,label])=><button key={direction} className={direction} onClick={()=>move(key)}>{label}</button>)}</div>{complete?<div className="labyrinth-complete"><b>THE LANTERN-DOOR OPENS</b><span>Clarity +18</span><button onClick={onExit}>LEAVE THE LABYRINTH</button></div>:<button className="leave-practice" onClick={onExit}>RETREAT TO THE TUNNEL MOUTH</button>}</section>
}
