import {useCallback,useEffect,useRef,useState} from 'react';
import {clampMeter,type GameStats} from '../game/gameState';
import './GameMode.css';
import './TraumaLabyrinth.css';

const maze=['###############','#S#.....#.....#','#.#.###.#.###.#','#...#...#...#.#','###.#.#####.#.#','#...#.....#.#.#','#.#######.#.#.#','#.....#...#...#','#.###.#.#####.#','#...#........E#','###############'];
const symbols=new Map<string,{glyph:string;name:string}>([
 ['3,1',{glyph:'♢',name:'False Door'}],['7,3',{glyph:'⚡',name:'Flashback'}],['11,3',{glyph:'⌁',name:'Echo Knot'}],['5,5',{glyph:'◐',name:'Half-Seen Face'}],
 ['9,5',{glyph:'☂',name:'Shelter Switch'}],['5,7',{glyph:'✧',name:'Grounding Star'}],['11,7',{glyph:'◒',name:'Repeating Scene'}],['7,9',{glyph:'⛓',name:'Old Bindings'}]
]);
const directions={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]} as const;
const opposite:Record<keyof typeof directions,keyof typeof directions>={ArrowUp:'ArrowDown',ArrowDown:'ArrowUp',ArrowLeft:'ArrowRight',ArrowRight:'ArrowLeft',w:'s',s:'w',a:'d',d:'a'};
const phaseOpen=[new Set(['4,1','8,5']),new Set(['6,7','12,5'])];
const keyOf=(x:number,y:number)=>`${x},${y}`;

export default function TraumaLabyrinth({stats,onChange,onExit}:{stats:GameStats;onChange:(stats:GameStats)=>void;onExit:()=>void}){
 const latest=useRef(stats),checkpoint=useRef({x:1,y:1}),reverseMoves=useRef(0),[position,setPosition]=useState({x:1,y:1}),[visited,setVisited]=useState(()=>new Set(['1,1'])),[complete,setComplete]=useState(false),[grounded,setGrounded]=useState(false),[shifted,setShifted]=useState(false),[message,setMessage]=useState('The lantern shows only the next few stones. The symbols are rules, not decorations.'),[messageTone,setMessageTone]=useState<'quiet'|'danger'|'shelter'>('quiet'),[steps,setSteps]=useState(0);latest.current=stats;
 useEffect(()=>{if(complete)return;const timer=window.setInterval(()=>{const next={...latest.current,concentration:clampMeter(latest.current.concentration-.38)};latest.current=next;onChange(next)},1000);return()=>clearInterval(timer)},[complete,onChange]);
 const speak=(copy:string,tone:'quiet'|'danger'|'shelter'='quiet')=>{setMessage(copy);setMessageTone(tone)};
 const move=useCallback((raw:keyof typeof directions)=>{if(complete)return;const reversed=reverseMoves.current>0,key=reversed?opposite[raw]:raw;if(reversed)reverseMoves.current--;const [dx,dy]=directions[key],x=position.x+dx,y=position.y+dy,cellKey=keyOf(x,y),baseWall=maze[y]?.[x]==='#',opened=phaseOpen[shifted?1:0].has(cellKey);
  if(baseWall&&!opened){speak(shifted?'The changed tunnel closes here. Somewhere else, stone has remembered a door.':'Cold stone. This route belongs to another shape of the labyrinth.');return}
  if(cellKey==='5,5'){speak('The Half-Seen Face fills the corridor. Looking harder does not move it; another route remains.','danger');return}
  if(cellKey==='7,9'&&!grounded){speak('Old Bindings pull tight across the passage. Find something present-tense and bright.','danger');return}
  const nextStats={...latest.current,concentration:clampMeter(latest.current.concentration-.52)};latest.current=nextStats;onChange(nextStats);let destination={x,y};setSteps(value=>value+1);
  if(cellKey==='3,1'||cellKey==='7,3'){destination={x:1,y:1};checkpoint.current={x:1,y:1};speak(cellKey==='3,1'?'The painted doorway opens onto the entrance. Familiar is not always forward.':'The flash arrives before the present can answer. When the light returns, you are at the mouth of the tunnel.','danger')}
  else if(cellKey==='11,3'){reverseMoves.current=8;speak('The Echo Knot catches direction itself. For eight steps, left remembers right and forward remembers back.','danger')}
  else if(cellKey==='9,5'){const nextShift=!shifted;setShifted(nextShift);checkpoint.current={x,y};speak(`Inside the shelter, you move one old chair. The whole tunnel quietly becomes Pattern ${nextShift?'B':'A'}.`,'shelter')}
  else if(cellKey==='5,7'&&!grounded){setGrounded(true);speak('A plain star: feet, breath, stone, now. The Old Bindings cannot pretend the past is the present anymore.','shelter')}
  else if(cellKey==='11,7'){destination=checkpoint.current;speak('The scene repeats—but the Shelter remembers you. You return to the last safe place, not the beginning.','danger')}
  setPosition(destination);setVisited(previous=>{const next=new Set(previous);next.add(cellKey);next.add(keyOf(destination.x,destination.y));return next});
  if(maze[y]?.[x]==='E'){const reward={...nextStats,clarity:clampMeter(nextStats.clarity+18),integration:clampMeter((nextStats.integration??0)+4)};latest.current=reward;onChange(reward);setComplete(true);speak('The Lantern-Door opens. The tunnel is remembered, but it is no longer the whole world.','shelter')}
 },[complete,grounded,onChange,position,shifted]);
 useEffect(()=>{const down=(event:KeyboardEvent)=>{const key=(event.key.length===1?event.key.toLowerCase():event.key) as keyof typeof directions;if(key in directions){event.preventDefault();move(key)}};addEventListener('keydown',down);return()=>removeEventListener('keydown',down)},[move]);
 const openCells=phaseOpen[shifted?1:0],objective=grounded?'REACH THE LANTERN-DOOR':'FIND THE GROUNDING STAR';
 return <section className="trauma-game trauma-labyrinth" role="dialog" aria-label="Trauma Tunnels Labyrinth"><header className={messageTone}><small>THE TRAUMA TUNNELS · PATTERN {shifted?'B':'A'}</small><h2>THE LABYRINTH OF ECHOES</h2><p>{message}</p></header><div className="trauma-objective"><span>{objective}</span><i>{grounded?'STAR HELD':'STAR UNFOUND'}</i><b>{reverseMoves.current>0?`DIRECTIONS REVERSED · ${reverseMoves.current}`:`${steps} STEPS REMEMBERED`}</b></div><div className="trauma-layout"><div className="maze-frame"><div className="tunnel-torch left"/><div className="tunnel-torch right"/><div className="maze" style={{gridTemplateColumns:`repeat(${maze[0].length},1fr)`}}>{maze.flatMap((row,y)=>[...row].map((cell,x)=>{const key=keyOf(x,y),symbol=symbols.get(key),here=position.x===x&&position.y===y,isOpen=openCells.has(key),wall=cell==='#'&&!isOpen,locked=key==='7,9'&&!grounded,distance=Math.hypot(position.x-x,position.y-y),seen=visited.has(key),visible=distance<3.2||seen||cell==='S';return <div key={key} title={symbol?.name} className={`maze-cell ${wall?'wall':'floor'} ${isOpen?'shift-passage':''} ${cell==='E'?'exit':''} ${locked?'locked':''} ${visible?'revealed':'unseen'} ${seen?'visited':''}`}>{visible&&symbol&&<span aria-label={symbol.name}>{symbol.glyph}</span>}{cell==='E'&&visible&&<b>◇</b>}{here&&<div className="tunnel-wizard"><i/><b/></div>}</div>}))}</div></div><aside className="trauma-symbols"><b>THE TUNNEL’S GRAMMAR</b><span><i>♢</i> False Door <em>returns to beginning</em></span><span><i>⚡</i> Flashback <em>tears away the route</em></span><span><i>◐</i> Half-Seen Face <em>blocks what looked open</em></span><span><i>⌁</i> Echo Knot <em>reverses direction</em></span><span><i>☂</i> Shelter Switch <em>changes the walls</em></span><span><i>✧</i> Grounding Star <em>opens old bindings</em></span><span><i>◒</i> Repeating Scene <em>returns to shelter</em></span><span><i>⛓</i> Old Bindings <em>yield to grounding</em></span></aside></div><div className="trauma-readout"><span>LANTERN FUEL</span><div><i style={{width:`${latest.current.concentration}%`}}/></div><b>{Math.round(latest.current.concentration)}</b></div><div className="trauma-controls">{([['up','ArrowUp','▲'],['left','ArrowLeft','◀'],['down','ArrowDown','▼'],['right','ArrowRight','▶']] as const).map(([direction,key,label])=><button key={direction} className={direction} onClick={()=>move(key)}>{label}</button>)}</div>{complete?<div className="labyrinth-complete"><small>THE PRESENT HOLDS</small><b>THE LANTERN-DOOR OPENS</b><span>Clarity +18 · Integration +4</span><button onClick={onExit}>LEAVE THE LABYRINTH</button></div>:<button className="leave-practice" onClick={onExit}>RETREAT TO THE TUNNEL MOUTH</button>}</section>;
}
