import {mapRegions,WORLD,type Region,type TerrainType} from '../data/mapRegions';
import {routes} from '../data/routes';import {drawRoutes} from './drawRoutes';import {hashNoise} from '../engine/terrainEffects';
import {regionExtent} from '../engine/regionGeometry';
import {drawAtlasCell,drawStateCell,drawStoryCell,getAtlas} from './pixelArtAssets';
import {ambientProps,mapProps} from '../data/mapProps';
import {mistWisps,regionVisuals} from '../data/regionVisuals';
const colors:Record<TerrainType,string>={home:'#d7773d',garden:'#79a84c',range:'#b58a50',mist:'#778995',lagoon:'#527f76',tunnel:'#55475d',chasm:'#211d29',inn:'#8d633c',peak:'#9e4938',tower:'#788da0',hills:'#9ebd55',void:'#171831',meadow:'#7dbd71',celestial:'#b8d9d5',magical:'#844f87',memory:'#86738e'};
const terrainCells:Record<TerrainType,[number,number]>={home:[3,0],garden:[1,0],range:[2,0],mist:[0,1],lagoon:[1,1],tunnel:[2,1],chasm:[2,1],inn:[3,0],peak:[3,1],tower:[0,2],hills:[1,2],void:[2,2],meadow:[3,2],celestial:[0,3],magical:[1,3],memory:[0,2]};
function traceRegion(ctx:CanvasRenderingContext2D,r:Region){ctx.beginPath();if(r.shape.kind==='polygon')r.shape.points.forEach(([x,y],i)=>i?ctx.lineTo(r.x+x,r.y+y):ctx.moveTo(r.x+x,r.y+y));else for(let i=0;i<20;i++){const a=i/20*Math.PI*2,rr=r.shape.radius*(.86+hashNoise(i,r.x)*.19),x=r.x+Math.cos(a)*rr,y=r.y+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath()}
function tileTexture(ctx:CanvasRenderingContext2D,image:HTMLImageElement,column:number,row:number,left:number,top:number,right:number,bottom:number,tileSize:number){const sourceW=image.naturalWidth/4,sourceH=image.naturalHeight/4,startX=Math.floor(left/tileSize)*tileSize,startY=Math.floor(top/tileSize)*tileSize;for(let y=startY;y<bottom;y+=tileSize)for(let x=startX;x<right;x+=tileSize)ctx.drawImage(image,column*sourceW,row*sourceH,sourceW,sourceH,x,y,tileSize,tileSize)}
function blob(ctx:CanvasRenderingContext2D,r:Region){const extent=regionExtent(r),atlas=getAtlas('terrain'),cell=terrainCells[r.terrain];ctx.save();traceRegion(ctx,r);ctx.fillStyle=colors[r.terrain];ctx.fill();if(atlas){ctx.clip();ctx.globalAlpha=.76;tileTexture(ctx,atlas,cell[0],cell[1],r.x-extent,r.y-extent,r.x+extent,r.y+extent,96);ctx.globalAlpha=1}ctx.restore();ctx.save();traceRegion(ctx,r);ctx.strokeStyle='rgba(16,20,22,.26)';ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle='rgba(255,239,190,.12)';ctx.lineWidth=1;ctx.stroke();ctx.restore();}
function landmark(ctx:CanvasRenderingContext2D,r:Region){ctx.save();ctx.translate(r.x,r.y);ctx.fillStyle='#f5d67a';
 if(r.terrain==='home'){ctx.fillStyle='#7b3d2b';ctx.fillRect(-26,-20,52,40);ctx.fillStyle='#dc7037';ctx.beginPath();ctx.moveTo(-34,-20);ctx.lineTo(0,-48);ctx.lineTo(34,-20);ctx.fill();ctx.fillStyle='#ffd66b';ctx.fillRect(-7,4,14,16)}
 if(r.terrain==='range'){ctx.fillStyle='#e8d8a8';ctx.fillRect(-32,18,64,4);ctx.fillStyle='#842d2b';ctx.fillRect(13,-20,5,38);ctx.fillStyle='#f1d7a4';ctx.fillRect(3,-29,24,24);ctx.fillStyle='#df3434';ctx.fillRect(10,-22,10,10)}
 if(r.terrain==='tower'){ctx.fillStyle='#e0d2ad';ctx.fillRect(-25,-55,50,85);ctx.fillStyle='#596379';ctx.fillRect(-34,-65,68,18);ctx.fillStyle='#ffdf72';ctx.fillRect(-6,-35,12,18)}
 if(r.terrain==='peak'){ctx.fillStyle='#4b3f49';ctx.beginPath();ctx.moveTo(-65,45);ctx.lineTo(0,-55);ctx.lineTo(70,45);ctx.fill();ctx.fillStyle='#f0643e';ctx.fillRect(-12,-58,24,18);for(let i=0;i<8;i++){ctx.fillStyle=i%2?'#ffd966':'#ec5f67';ctx.fillRect(Math.cos(i)*50,-75+Math.sin(i)*30,6,6)}}
 if(r.terrain==='celestial'){ctx.fillStyle='#f5f0c4';for(let i=-2;i<3;i++)ctx.fillRect(i*30-25,Math.abs(i)*8-18,50,24)}
 if(r.terrain==='hills'){ctx.strokeStyle='#f1e37b';ctx.lineWidth=10;ctx.beginPath();ctx.arc(0,0,70,Math.PI,0);ctx.stroke();}
 if(r.terrain==='void'){ctx.fillStyle='#c9b9ff';for(let i=0;i<18;i++)ctx.fillRect(hashNoise(i,4)*210-105,hashNoise(i,8)*180-90,4,4)}
 if(r.terrain==='magical'){ctx.strokeStyle='#f19fe7';ctx.lineWidth=7;ctx.strokeRect(-38,-38,76,76);ctx.rotate(Math.PI/4);ctx.strokeRect(-28,-28,56,56)}ctx.restore();}
const landmarkCells:Record<string,[number,number]>={house:[0,0],garden:[1,0],'red-dot':[2,0],mist:[3,0],booboo:[0,1],trauma:[1,1],fireworks:[2,1],tower:[3,1],jhana:[0,2],formless:[1,2],healing:[2,2],celestial:[3,2],magical:[0,3]};
const expansionCells:Record<string,[number,number]>={chasm:[0,0],inn:[1,0]};
function landmarkArt(ctx:CanvasRenderingContext2D,r:Region){if(r.id==='life-recall'){const atlas=getAtlas('states'),visual=regionVisuals[r.id],size=visual?.artSize??150;if(!atlas)return false;drawStateCell(ctx,atlas,0,0,r.x,r.y,size);return true}if(r.id==='healing'){const atlas=getAtlas('special'),visual=regionVisuals.healing,size=visual?.artSize??150;if(!atlas)return false;ctx.drawImage(atlas,0,0,atlas.naturalWidth/4,atlas.naturalHeight/2,r.x-size/2,r.y-size/2,size,size);return true}const isExpansion=!!expansionCells[r.id],atlas=getAtlas(isExpansion?'expansion':'landmarks'),cell=(isExpansion?expansionCells:landmarkCells)[r.id];if(!atlas||!cell)return false;if(r.id==='mist'){for(const [x,y,size] of mistWisps)drawAtlasCell(ctx,atlas,cell[0],cell[1],x,y,size);return true}const extent=regionExtent(r),visual=regionVisuals[r.id],size=visual?.artSize??Math.max(120,Math.min(230,extent*1.45)),[offsetX,offsetY]=visual?.artOffset??[0,0];drawAtlasCell(ctx,atlas,cell[0],cell[1],r.x+offsetX,r.y+offsetY,size);return true}
function storyProps(ctx:CanvasRenderingContext2D){const atlas=getAtlas('story');if(!atlas)return;for(const prop of ambientProps){ctx.save();ctx.globalAlpha=prop.alpha;drawStoryCell(ctx,atlas,...prop.art,prop.x,prop.y,prop.size);ctx.restore()}for(const prop of mapProps)drawStoryCell(ctx,atlas,...prop.art,prop.x,prop.y,prop.size)}
export function drawMap(ctx:CanvasRenderingContext2D,showLabels:boolean){ctx.fillStyle='#374f3a';ctx.fillRect(0,0,WORLD.width,WORLD.height);const terrain=getAtlas('terrain');if(terrain){ctx.save();ctx.globalAlpha=.82;tileTexture(ctx,terrain,0,0,0,0,WORLD.width,WORLD.height,128);ctx.restore()}else for(let y=10;y<WORLD.height;y+=32)for(let x=10;x<WORLD.width;x+=32){const n=hashNoise(x,y);ctx.fillStyle=n>.7?'#426043':'#314a35';ctx.fillRect(x+(n*8|0),y,3,8)}
 for(const r of [...mapRegions].sort((a,b)=>a.layer-b.layer))blob(ctx,r);drawRoutes(ctx,routes);storyProps(ctx);for(const r of [...mapRegions].sort((a,b)=>a.layer-b.layer))if(!landmarkArt(ctx,r))landmark(ctx,r);
 if(showLabels){ctx.font='bold 16px monospace';ctx.textAlign='center';ctx.textBaseline='top';ctx.lineJoin='round';for(const r of mapRegions){const visual=regionVisuals[r.id],[offsetX,offsetY]=visual?.labelOffset??[0,r.terrain==='home'?28:Math.min(regionExtent(r)*.55,75)],x=r.x+offsetX,y=r.y+offsetY;ctx.strokeStyle='rgba(12,13,17,.9)';ctx.lineWidth=5;ctx.strokeText(r.name,x,y);ctx.fillStyle='#fff1bb';ctx.fillText(r.name,x,y)}}}
