import {useCallback,useEffect,useRef,useState} from 'react';
import {mapRegions,WORLD,type Region} from './data/mapRegions';import {presentationContent} from './data/presentationContent';
import {movePlayer,type Player} from './engine/movement';import {mapCamera,playerCamera,type View} from './engine/camera';
import {drawMap} from './rendering/drawMap';import {drawPlayer} from './rendering/drawPlayer';import {drawVignette} from './rendering/drawUI';
type Mode='player'|'presentation';
const startPlayer:Player={x:915,y:510,direction:'down',moving:false,step:0};
export default function App(){const [started,setStarted]=useState(false),[mode,setMode]=useState<Mode>('player'),[selected,setSelected]=useState<Region|null>(null);const canvasRef=useRef<HTMLCanvasElement>(null),player=useRef(startPlayer),keys=useRef(new Set<string>()),view=useRef<View>({x:0,y:0,scale:1}),activeRegion=useRef<string|null>(null);
 const virtualKey=(key:string,pressed:boolean)=>{if(pressed)keys.current.add(key);else keys.current.delete(key)};
 const resize=useCallback(()=>{const c=canvasRef.current;if(!c)return;const d=devicePixelRatio||1,box=c.getBoundingClientRect();c.width=Math.round(box.width*d);c.height=Math.round(box.height*d)},[]);
 useEffect(()=>{resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[resize]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.current.add(e.key.toLowerCase())}if(e.key==='Escape')setSelected(null)};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[]);
 useEffect(()=>{if(!started)return;let frame=0,last=performance.now();const tick=(now:number)=>{const c=canvasRef.current;if(!c)return;const dt=Math.min((now-last)/1000,.04);last=now;const d=devicePixelRatio||1,w=c.width/d,h=c.height/d,ctx=c.getContext('2d')!;ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,w,h);
   if(mode==='player'&&!selected)player.current=movePlayer(player.current,keys.current,dt,WORLD.width,WORLD.height);view.current=mode==='player'?playerCamera(player.current.x,player.current.y,w,h,WORLD.width,WORLD.height):mapCamera(w,h,WORLD.width,WORLD.height);
   if(mode==='player'){const entered=mapRegions.filter(r=>Math.hypot(player.current.x-r.x,player.current.y-r.y)<r.radius).sort((a,b)=>a.radius-b.radius)[0]??null;if(entered?.id!==(activeRegion.current??undefined)){activeRegion.current=entered?.id??null;if(entered)setSelected(entered)}}
   const v=view.current;ctx.save();ctx.scale(v.scale,v.scale);ctx.translate(-v.x,-v.y);const nearby=mapRegions.some(r=>Math.hypot(player.current.x-r.x,player.current.y-r.y)<r.radius+100);drawMap(ctx,mode==='presentation'||nearby);if(mode==='player')drawPlayer(ctx,player.current);ctx.restore();drawVignette(ctx,w,h);frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[started,mode,selected,resize]);
 const clickCanvas=(e:React.MouseEvent<HTMLCanvasElement>)=>{if(mode!=='presentation'){canvasRef.current?.focus();return}const rect=e.currentTarget.getBoundingClientRect(),v=view.current,x=(e.clientX-rect.left)/v.scale+v.x,y=(e.clientY-rect.top)/v.scale+v.y;const hits=mapRegions.filter(r=>Math.hypot(x-r.x,y-r.y)<r.radius);setSelected(hits.sort((a,b)=>a.radius-b.radius)[0]??null)};
 if(!started)return <main className="title-screen"><div className="embers"/><section className="title-card"><div className="flame">◆</div><p className="eyebrow">AN INTERACTIVE FIRE KASINA MAP</p><h1>FIRE KASINA <span>is about to have an adventure called</span> YOU</h1><p className="subtitle">Beyond the garden, the wilderness of mind is waiting.</p><button onClick={()=>setStarted(true)}>BEGIN THE ADVENTURE</button><small>WASD / ARROW KEYS · CLICK TO EXPLORE</small></section></main>;
 return <main className="game"><canvas ref={canvasRef} tabIndex={0} onClick={clickCanvas}/><header><div><b>FIRE KASINA</b><span>THE MAP OF YOU</span></div><nav aria-label="Game mode"><button className={mode==='player'?'active':''} onClick={()=>{activeRegion.current=null;setMode('player');setSelected(null)}}>♟ PLAYER</button><button className={mode==='presentation'?'active':''} onClick={()=>{setMode('presentation');setSelected(null)}}>⌖ MAP</button></nav></header><aside className="help">{mode==='player'?<>MOVE <kbd>WASD</kbd> <kbd>↑↓←→</kbd></>:<>TAP A REGION TO EXPLORE</>}</aside>{mode==='player'&&<div className="dpad" aria-label="Touch movement controls">{(['up','left','down','right'] as const).map(direction=><button key={direction} className={direction} aria-label={`Move ${direction}`} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);virtualKey(direction==='up'?'w':direction==='left'?'a':direction==='down'?'s':'d',true)}} onPointerUp={()=>virtualKey(direction==='up'?'w':direction==='left'?'a':direction==='down'?'s':'d',false)} onPointerCancel={()=>virtualKey(direction==='up'?'w':direction==='left'?'a':direction==='down'?'s':'d',false)}>{direction==='up'?'▲':direction==='left'?'◀':direction==='down'?'▼':'▶'}</button>)}</div>}{selected&&<section className="bubble dialogue" role="dialog" aria-live="polite" aria-label={selected.name}><button aria-label="Close dialogue" onClick={()=>setSelected(null)}>×</button><p>{mode==='player'?'AREA DISCOVERED':'MAP LORE'}</p><h2>{selected.name}</h2><div className="rule"/><p className="copy"><span className="dialogue-gem">◆</span>{presentationContent[selected.id]}</p><small className="dialogue-hint">{mode==='player'?'CLOSE TO CONTINUE':'TAP OUTSIDE OR × TO CLOSE'}</small></section>}</main>;
}
