import {useCallback,useEffect,useRef,useState} from 'react';
import {mapRegions,WORLD,type Region} from './data/mapRegions';import {presentationContent} from './data/presentationContent';
import {movePlayer,type Player} from './engine/movement';import {mapCamera,playerCamera,type View} from './engine/camera';
import {drawMap} from './rendering/drawMap';import {drawPlayer} from './rendering/drawPlayer';import {drawVignette} from './rendering/drawUI';
type Mode='player'|'presentation';
const startPlayer:Player={x:915,y:510,direction:'down',moving:false,step:0};
export default function App(){const [started,setStarted]=useState(false),[mode,setMode]=useState<Mode>('player'),[selected,setSelected]=useState<Region|null>(null);const canvasRef=useRef<HTMLCanvasElement>(null),player=useRef(startPlayer),keys=useRef(new Set<string>()),view=useRef<View>({x:0,y:0,scale:1}),mapView=useRef<View|null>(null),activeRegion=useRef<string|null>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),gestureMoved=useRef(false);
 const virtualKey=(key:string,pressed:boolean)=>{if(pressed)keys.current.add(key);else keys.current.delete(key)};
 const resize=useCallback(()=>{const c=canvasRef.current;if(!c)return;const d=devicePixelRatio||1,box=c.getBoundingClientRect();c.width=Math.round(box.width*d);c.height=Math.round(box.height*d);mapView.current=null},[]);
 useEffect(()=>{resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[resize]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.current.add(e.key.toLowerCase())}if(e.key==='Escape')setSelected(null)};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[]);
 useEffect(()=>{if(!started)return;let frame=0,last=performance.now();const tick=(now:number)=>{const c=canvasRef.current;if(!c)return;const dt=Math.min((now-last)/1000,.04);last=now;const d=devicePixelRatio||1,w=c.width/d,h=c.height/d,ctx=c.getContext('2d')!;ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,w,h);
   if(mode==='player'&&!selected)player.current=movePlayer(player.current,keys.current,dt,WORLD.width,WORLD.height);if(mode==='player')view.current=playerCamera(player.current.x,player.current.y,w,h,WORLD.width,WORLD.height);else {mapView.current??=mapCamera(w,h,WORLD.width,WORLD.height);view.current=mapView.current}
   if(mode==='player'){const entered=mapRegions.filter(r=>Math.hypot(player.current.x-r.x,player.current.y-r.y)<r.radius).sort((a,b)=>a.radius-b.radius)[0]??null;if(entered?.id!==(activeRegion.current??undefined)){activeRegion.current=entered?.id??null;if(entered)setSelected(entered)}}
   const v=view.current;ctx.save();ctx.scale(v.scale,v.scale);ctx.translate(-v.x,-v.y);const nearby=mapRegions.some(r=>Math.hypot(player.current.x-r.x,player.current.y-r.y)<r.radius+100);drawMap(ctx,mode==='presentation'||nearby);if(mode==='player')drawPlayer(ctx,player.current);ctx.restore();drawVignette(ctx,w,h);frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[started,mode,selected,resize]);
 const clampMapView=(next:View)=>{const box=canvasRef.current?.getBoundingClientRect();if(!box)return next;const fit=mapCamera(box.width,box.height,WORLD.width,WORLD.height),scale=Math.max(fit.scale,Math.min(fit.scale*5,next.scale)),visibleW=box.width/scale,visibleH=box.height/scale;return{x:visibleW>=WORLD.width?(WORLD.width-visibleW)/2:Math.max(0,Math.min(WORLD.width-visibleW,next.x)),y:visibleH>=WORLD.height?(WORLD.height-visibleH)/2:Math.max(0,Math.min(WORLD.height-visibleH,next.y)),scale}};
 const pickMapRegion=(clientX:number,clientY:number)=>{const c=canvasRef.current;if(mode!=='presentation'||!c)return;const rect=c.getBoundingClientRect(),v=mapView.current??view.current,sx=clientX-rect.left,sy=clientY-rect.top;const hit=mapRegions.map(region=>{const distance=Math.hypot(sx-(region.x-v.x)*v.scale,sy-(region.y-v.y)*v.scale),targetRadius=Math.max(52,region.radius*v.scale);return{region,score:distance/targetRadius}}).filter(candidate=>candidate.score<=1).sort((a,b)=>a.score-b.score||a.region.radius-b.region.radius)[0];setSelected(hit?.region??null)};
 const zoomMap=(factor:number,screenX?:number,screenY?:number)=>{const c=canvasRef.current;if(!c)return;const rect=c.getBoundingClientRect(),current=mapView.current??mapCamera(rect.width,rect.height,WORLD.width,WORLD.height),cx=screenX??rect.width/2,cy=screenY??rect.height/2,worldX=current.x+cx/current.scale,worldY=current.y+cy/current.scale,nextScale=current.scale*factor;mapView.current=clampMapView({x:worldX-cx/nextScale,y:worldY-cy/nextScale,scale:nextScale})};
 const pointerDown=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(mode!=='presentation'){canvasRef.current?.focus();return}e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);if(pointers.current.size===0)gestureMoved.current=false;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY})};
 const pointerMove=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(mode!=='presentation')return;const previous=pointers.current.get(e.pointerId);if(!previous)return;e.preventDefault();const before=[...pointers.current.values()];pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const after=[...pointers.current.values()],rect=e.currentTarget.getBoundingClientRect(),current=mapView.current??mapCamera(rect.width,rect.height,WORLD.width,WORLD.height);if(Math.hypot(e.clientX-previous.x,e.clientY-previous.y)>3)gestureMoved.current=true;if(after.length===1){mapView.current=clampMapView({...current,x:current.x-(e.clientX-previous.x)/current.scale,y:current.y-(e.clientY-previous.y)/current.scale})}else if(after.length>=2){gestureMoved.current=true;const oldDistance=Math.hypot(before[0].x-before[1].x,before[0].y-before[1].y),newDistance=Math.hypot(after[0].x-after[1].x,after[0].y-after[1].y);if(oldDistance>0){const centerX=(after[0].x+after[1].x)/2-rect.left,centerY=(after[0].y+after[1].y)/2-rect.top,worldX=current.x+centerX/current.scale,worldY=current.y+centerY/current.scale,nextScale=current.scale*newDistance/oldDistance;mapView.current=clampMapView({x:worldX-centerX/nextScale,y:worldY-centerY/nextScale,scale:nextScale})}}};
 const pointerUp=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(mode!=='presentation')return;const isTap=pointers.current.size===1&&!gestureMoved.current;pointers.current.delete(e.pointerId);if(isTap)pickMapRegion(e.clientX,e.clientY);if(pointers.current.size===0)gestureMoved.current=false};
 const pointerCancel=(e:React.PointerEvent<HTMLCanvasElement>)=>{pointers.current.delete(e.pointerId);if(pointers.current.size===0)gestureMoved.current=false};
 if(!started)return <main className="title-screen"><div className="embers"/><section className="title-card"><div className="flame">◆</div><p className="eyebrow">AN INTERACTIVE FIRE KASINA MAP</p><h1>FIRE KASINA <span>is about to have an adventure called</span> YOU</h1><p className="subtitle">Beyond the garden, the wilderness of mind is waiting.</p><button onClick={()=>setStarted(true)}>BEGIN THE ADVENTURE</button><small>WASD / ARROW KEYS · CLICK TO EXPLORE</small></section></main>;
 return <main className="game"><canvas ref={canvasRef} tabIndex={0} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerCancel}/><header><div><b>FIRE KASINA</b><span>THE MAP OF YOU</span></div><nav aria-label="Game mode"><button className={mode==='player'?'active':''} onClick={()=>{activeRegion.current=null;pointers.current.clear();setMode('player');setSelected(null)}}>♟ PLAYER</button><button className={mode==='presentation'?'active':''} onClick={()=>{mapView.current=null;pointers.current.clear();setMode('presentation');setSelected(null)}}>⌖ MAP</button></nav></header><aside className="help">{mode==='player'?<>MOVE <kbd>WASD</kbd> <kbd>↑↓←→</kbd></>:<>TAP · DRAG · PINCH TO EXPLORE</>}</aside>{mode==='presentation'&&<div className="map-tools" aria-label="Map zoom controls"><button aria-label="Zoom in" onClick={()=>zoomMap(1.5)}>+</button><button aria-label="Zoom out" onClick={()=>zoomMap(1/1.5)}>−</button><button aria-label="Reset map view" onClick={()=>{mapView.current=null}}>⌂</button></div>}{mode==='player'&&<div className="dpad" aria-label="Touch movement controls">{(['up','left','down','right'] as const).map(direction=><button key={direction} className={direction} aria-label={`Move ${direction}`} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);virtualKey(direction==='up'?'w':direction==='left'?'a':direction==='down'?'s':'d',true)}} onPointerUp={()=>virtualKey(direction==='up'?'w':direction==='left'?'a':direction==='down'?'s':'d',false)} onPointerCancel={()=>virtualKey(direction==='up'?'w':direction==='left'?'a':direction==='down'?'s':'d',false)}>{direction==='up'?'▲':direction==='left'?'◀':direction==='down'?'▼':'▶'}</button>)}</div>}{selected&&<section className="bubble dialogue" role="dialog" aria-live="polite" aria-label={selected.name}><button aria-label="Close dialogue" onClick={()=>setSelected(null)}>×</button><p>{mode==='player'?'AREA DISCOVERED':'MAP LORE'}</p><h2>{selected.name}</h2><div className="rule"/><p className="copy"><span className="dialogue-gem">◆</span>{presentationContent[selected.id]}</p><small className="dialogue-hint">{mode==='player'?'CLOSE TO CONTINUE':'TAP OUTSIDE OR × TO CLOSE'}</small></section>}</main>;
}
